
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  ADMIN: 'ADMIN',
  PARTICIPANT: 'PARTICIPANT',
  GUEST: 'GUEST'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const MatchStage = {
  GROUP: 'GROUP',
  PLAYOFF: 'PLAYOFF',
  ROUND_OF_16: 'ROUND_OF_16',
  QUARTER_FINAL: 'QUARTER_FINAL',
  SEMI_FINAL: 'SEMI_FINAL',
  FINAL: 'FINAL'
} as const

export type MatchStage = (typeof MatchStage)[keyof typeof MatchStage]


export const MatchStatus = {
  SCHEDULED: 'SCHEDULED',
  LIVE: 'LIVE',
  FINISHED: 'FINISHED',
  CANCELED: 'CANCELED'
} as const

export type MatchStatus = (typeof MatchStatus)[keyof typeof MatchStatus]


export const WebhookEventType = {
  MATCH_STARTED: 'MATCH_STARTED',
  MATCH_FINISHED: 'MATCH_FINISHED',
  SCORE_UPDATED: 'SCORE_UPDATED',
  STANDINGS_UPDATED: 'STANDINGS_UPDATED',
  BRACKET_UPDATED: 'BRACKET_UPDATED'
} as const

export type WebhookEventType = (typeof WebhookEventType)[keyof typeof WebhookEventType]


export const BetOutcome = {
  HOME_WIN: 'HOME_WIN',
  DRAW: 'DRAW',
  AWAY_WIN: 'AWAY_WIN'
} as const

export type BetOutcome = (typeof BetOutcome)[keyof typeof BetOutcome]


export const BetStatus = {
  PENDING: 'PENDING',
  WON: 'WON',
  LOST: 'LOST',
  VOID: 'VOID',
  CANCELED: 'CANCELED',
  CREDIT_FAILED: 'CREDIT_FAILED'
} as const

export type BetStatus = (typeof BetStatus)[keyof typeof BetStatus]


export const RefundStatus = {
  PENDING: 'PENDING',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED'
} as const

export type RefundStatus = (typeof RefundStatus)[keyof typeof RefundStatus]


export const TransferStatus = {
  COMPLETED: 'COMPLETED',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED'
} as const

export type TransferStatus = (typeof TransferStatus)[keyof typeof TransferStatus]


export const NotificationType = {
  TRANSFER_RECEIVED: 'TRANSFER_RECEIVED',
  BET_WON: 'BET_WON',
  BET_REFUNDED: 'BET_REFUNDED',
  BET_CREDIT_FAILED: 'BET_CREDIT_FAILED',
  JOIN_REQUEST_RECEIVED: 'JOIN_REQUEST_RECEIVED',
  JOIN_REQUEST_ACCEPTED: 'JOIN_REQUEST_ACCEPTED',
  JOIN_REQUEST_REJECTED: 'JOIN_REQUEST_REJECTED',
  SYSTEM: 'SYSTEM'
} as const

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType]


export const JoinRequestStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED'
} as const

export type JoinRequestStatus = (typeof JoinRequestStatus)[keyof typeof JoinRequestStatus]


export const BettingMarketType = {
  MATCH_EXACT_SCORE: 'MATCH_EXACT_SCORE',
  MATCH_TOTAL_GOALS: 'MATCH_TOTAL_GOALS',
  MATCH_BTTS: 'MATCH_BTTS',
  MATCH_DRAW_NO_BET: 'MATCH_DRAW_NO_BET',
  MATCH_ODD_EVEN: 'MATCH_ODD_EVEN',
  TOURNAMENT_TOP_SCORER: 'TOURNAMENT_TOP_SCORER',
  TOURNAMENT_MVP: 'TOURNAMENT_MVP',
  TOURNAMENT_WINNER: 'TOURNAMENT_WINNER'
} as const

export type BettingMarketType = (typeof BettingMarketType)[keyof typeof BettingMarketType]


export const BettingMarketStatus = {
  OPEN: 'OPEN',
  LOCKED: 'LOCKED',
  SETTLED: 'SETTLED',
  VOID: 'VOID'
} as const

export type BettingMarketStatus = (typeof BettingMarketStatus)[keyof typeof BettingMarketStatus]


export const MatchEventType = {
  MATCH_STARTED: 'MATCH_STARTED',
  HALF_TIME: 'HALF_TIME',
  SECOND_HALF: 'SECOND_HALF',
  MATCH_ENDED: 'MATCH_ENDED',
  GOAL: 'GOAL',
  OWN_GOAL: 'OWN_GOAL',
  PENALTY_SCORED: 'PENALTY_SCORED',
  PENALTY_MISSED: 'PENALTY_MISSED',
  YELLOW_CARD: 'YELLOW_CARD',
  RED_CARD: 'RED_CARD',
  SUBSTITUTION: 'SUBSTITUTION',
  COMMENT: 'COMMENT'
} as const

export type MatchEventType = (typeof MatchEventType)[keyof typeof MatchEventType]
