
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Tournament: 'Tournament',
  Group: 'Group',
  Team: 'Team',
  Player: 'Player',
  Match: 'Match',
  MatchPlayerStats: 'MatchPlayerStats',
  Standing: 'Standing',
  Webhook: 'Webhook',
  MatchBettingPool: 'MatchBettingPool',
  Bet: 'Bet',
  BettingMarket: 'BettingMarket',
  MarketPool: 'MarketPool',
  MarketBet: 'MarketBet',
  BetSlip: 'BetSlip',
  MatchEvent: 'MatchEvent'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  username: 'username',
  avatar: 'avatar',
  role: 'role',
  clerkId: 'clerkId',
  twitchUsername: 'twitchUsername',
  twitchUserId: 'twitchUserId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const TournamentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  startDate: 'startDate',
  teamsPerGroup: 'teamsPerGroup',
  playersPerTeam: 'playersPerTeam',
  groupCount: 'groupCount',
  groupStageComplete: 'groupStageComplete',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TournamentScalarFieldEnum = (typeof TournamentScalarFieldEnum)[keyof typeof TournamentScalarFieldEnum]


export const GroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  position: 'position',
  tournamentId: 'tournamentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GroupScalarFieldEnum = (typeof GroupScalarFieldEnum)[keyof typeof GroupScalarFieldEnum]


export const TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  shortName: 'shortName',
  logo: 'logo',
  disqualified: 'disqualified',
  disqualificationReason: 'disqualificationReason',
  tournamentId: 'tournamentId',
  groupId: 'groupId',
  coachUserId: 'coachUserId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamScalarFieldEnum = (typeof TeamScalarFieldEnum)[keyof typeof TeamScalarFieldEnum]


export const PlayerScalarFieldEnum = {
  id: 'id',
  jerseyNumber: 'jerseyNumber',
  position: 'position',
  userId: 'userId',
  teamId: 'teamId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlayerScalarFieldEnum = (typeof PlayerScalarFieldEnum)[keyof typeof PlayerScalarFieldEnum]


export const MatchScalarFieldEnum = {
  id: 'id',
  stage: 'stage',
  status: 'status',
  matchDate: 'matchDate',
  homeScore: 'homeScore',
  awayScore: 'awayScore',
  winnerTeamId: 'winnerTeamId',
  twitchUrl: 'twitchUrl',
  discordUrl: 'discordUrl',
  youtubeUrl: 'youtubeUrl',
  streamTitle: 'streamTitle',
  groupId: 'groupId',
  tournamentId: 'tournamentId',
  homeTeamId: 'homeTeamId',
  awayTeamId: 'awayTeamId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MatchScalarFieldEnum = (typeof MatchScalarFieldEnum)[keyof typeof MatchScalarFieldEnum]


export const MatchPlayerStatsScalarFieldEnum = {
  id: 'id',
  goals: 'goals',
  assists: 'assists',
  yellowCards: 'yellowCards',
  redCards: 'redCards',
  matchId: 'matchId',
  playerId: 'playerId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MatchPlayerStatsScalarFieldEnum = (typeof MatchPlayerStatsScalarFieldEnum)[keyof typeof MatchPlayerStatsScalarFieldEnum]


export const StandingScalarFieldEnum = {
  id: 'id',
  position: 'position',
  played: 'played',
  won: 'won',
  drawn: 'drawn',
  lost: 'lost',
  goalsFor: 'goalsFor',
  goalsAgainst: 'goalsAgainst',
  points: 'points',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StandingScalarFieldEnum = (typeof StandingScalarFieldEnum)[keyof typeof StandingScalarFieldEnum]


export const WebhookScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  url: 'url',
  secret: 'secret',
  events: 'events',
  isActive: 'isActive',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  lastTriggeredAt: 'lastTriggeredAt',
  triggerCount: 'triggerCount',
  failureCount: 'failureCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WebhookScalarFieldEnum = (typeof WebhookScalarFieldEnum)[keyof typeof WebhookScalarFieldEnum]


export const MatchBettingPoolScalarFieldEnum = {
  id: 'id',
  matchId: 'matchId',
  totalHomePool: 'totalHomePool',
  totalDrawPool: 'totalDrawPool',
  totalAwayPool: 'totalAwayPool',
  betCount: 'betCount',
  uniqueBettors: 'uniqueBettors',
  housePercentage: 'housePercentage',
  finalTotalPool: 'finalTotalPool',
  lockedAt: 'lockedAt',
  settledAt: 'settledAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MatchBettingPoolScalarFieldEnum = (typeof MatchBettingPoolScalarFieldEnum)[keyof typeof MatchBettingPoolScalarFieldEnum]


export const BetScalarFieldEnum = {
  id: 'id',
  matchId: 'matchId',
  userId: 'userId',
  outcome: 'outcome',
  pickedTeamId: 'pickedTeamId',
  wizebotDebitTxId: 'wizebotDebitTxId',
  pointsWagered: 'pointsWagered',
  oddsAtPlacement: 'oddsAtPlacement',
  status: 'status',
  actualPayout: 'actualPayout',
  settledAt: 'settledAt',
  wizebotEventId: 'wizebotEventId',
  wizebotCreditTxId: 'wizebotCreditTxId',
  wizebotCreditError: 'wizebotCreditError',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BetScalarFieldEnum = (typeof BetScalarFieldEnum)[keyof typeof BetScalarFieldEnum]


export const BettingMarketScalarFieldEnum = {
  id: 'id',
  type: 'type',
  status: 'status',
  param: 'param',
  matchId: 'matchId',
  tournamentId: 'tournamentId',
  closesAt: 'closesAt',
  housePercentage: 'housePercentage',
  finalTotalPool: 'finalTotalPool',
  settledOutcomeKey: 'settledOutcomeKey',
  lockedAt: 'lockedAt',
  settledAt: 'settledAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BettingMarketScalarFieldEnum = (typeof BettingMarketScalarFieldEnum)[keyof typeof BettingMarketScalarFieldEnum]


export const MarketPoolScalarFieldEnum = {
  id: 'id',
  marketId: 'marketId',
  outcomeKey: 'outcomeKey',
  totalPool: 'totalPool',
  betCount: 'betCount',
  playerId: 'playerId',
  teamId: 'teamId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MarketPoolScalarFieldEnum = (typeof MarketPoolScalarFieldEnum)[keyof typeof MarketPoolScalarFieldEnum]


export const MarketBetScalarFieldEnum = {
  id: 'id',
  marketId: 'marketId',
  userId: 'userId',
  outcomeKey: 'outcomeKey',
  pointsWagered: 'pointsWagered',
  oddsAtPlacement: 'oddsAtPlacement',
  status: 'status',
  actualPayout: 'actualPayout',
  settledAt: 'settledAt',
  slipId: 'slipId',
  wizebotDebitTxId: 'wizebotDebitTxId',
  wizebotCreditTxId: 'wizebotCreditTxId',
  wizebotCreditError: 'wizebotCreditError',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MarketBetScalarFieldEnum = (typeof MarketBetScalarFieldEnum)[keyof typeof MarketBetScalarFieldEnum]


export const BetSlipScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  totalStake: 'totalStake',
  combinedOdds: 'combinedOdds',
  potentialPayout: 'potentialPayout',
  actualPayout: 'actualPayout',
  status: 'status',
  settledAt: 'settledAt',
  wizebotDebitTxId: 'wizebotDebitTxId',
  wizebotCreditTxId: 'wizebotCreditTxId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BetSlipScalarFieldEnum = (typeof BetSlipScalarFieldEnum)[keyof typeof BetSlipScalarFieldEnum]


export const MatchEventScalarFieldEnum = {
  id: 'id',
  matchId: 'matchId',
  type: 'type',
  minute: 'minute',
  teamId: 'teamId',
  playerId: 'playerId',
  description: 'description',
  createdById: 'createdById',
  createdAt: 'createdAt'
} as const

export type MatchEventScalarFieldEnum = (typeof MatchEventScalarFieldEnum)[keyof typeof MatchEventScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

