
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MarketBet` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model MarketBet
 * 
 */
export type MarketBetModel = runtime.Types.Result.DefaultSelection<Prisma.$MarketBetPayload>

export type AggregateMarketBet = {
  _count: MarketBetCountAggregateOutputType | null
  _avg: MarketBetAvgAggregateOutputType | null
  _sum: MarketBetSumAggregateOutputType | null
  _min: MarketBetMinAggregateOutputType | null
  _max: MarketBetMaxAggregateOutputType | null
}

export type MarketBetAvgAggregateOutputType = {
  pointsWagered: number | null
  oddsAtPlacement: runtime.Decimal | null
  actualPayout: number | null
}

export type MarketBetSumAggregateOutputType = {
  pointsWagered: number | null
  oddsAtPlacement: runtime.Decimal | null
  actualPayout: number | null
}

export type MarketBetMinAggregateOutputType = {
  id: string | null
  marketId: string | null
  userId: string | null
  outcomeKey: string | null
  pointsWagered: number | null
  oddsAtPlacement: runtime.Decimal | null
  source: $Enums.BetSource | null
  status: $Enums.BetStatus | null
  actualPayout: number | null
  settledAt: Date | null
  slipId: string | null
  wizebotDebitTxId: string | null
  wizebotCreditTxId: string | null
  wizebotCreditError: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MarketBetMaxAggregateOutputType = {
  id: string | null
  marketId: string | null
  userId: string | null
  outcomeKey: string | null
  pointsWagered: number | null
  oddsAtPlacement: runtime.Decimal | null
  source: $Enums.BetSource | null
  status: $Enums.BetStatus | null
  actualPayout: number | null
  settledAt: Date | null
  slipId: string | null
  wizebotDebitTxId: string | null
  wizebotCreditTxId: string | null
  wizebotCreditError: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MarketBetCountAggregateOutputType = {
  id: number
  marketId: number
  userId: number
  outcomeKey: number
  pointsWagered: number
  oddsAtPlacement: number
  source: number
  status: number
  actualPayout: number
  settledAt: number
  slipId: number
  wizebotDebitTxId: number
  wizebotCreditTxId: number
  wizebotCreditError: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MarketBetAvgAggregateInputType = {
  pointsWagered?: true
  oddsAtPlacement?: true
  actualPayout?: true
}

export type MarketBetSumAggregateInputType = {
  pointsWagered?: true
  oddsAtPlacement?: true
  actualPayout?: true
}

export type MarketBetMinAggregateInputType = {
  id?: true
  marketId?: true
  userId?: true
  outcomeKey?: true
  pointsWagered?: true
  oddsAtPlacement?: true
  source?: true
  status?: true
  actualPayout?: true
  settledAt?: true
  slipId?: true
  wizebotDebitTxId?: true
  wizebotCreditTxId?: true
  wizebotCreditError?: true
  createdAt?: true
  updatedAt?: true
}

export type MarketBetMaxAggregateInputType = {
  id?: true
  marketId?: true
  userId?: true
  outcomeKey?: true
  pointsWagered?: true
  oddsAtPlacement?: true
  source?: true
  status?: true
  actualPayout?: true
  settledAt?: true
  slipId?: true
  wizebotDebitTxId?: true
  wizebotCreditTxId?: true
  wizebotCreditError?: true
  createdAt?: true
  updatedAt?: true
}

export type MarketBetCountAggregateInputType = {
  id?: true
  marketId?: true
  userId?: true
  outcomeKey?: true
  pointsWagered?: true
  oddsAtPlacement?: true
  source?: true
  status?: true
  actualPayout?: true
  settledAt?: true
  slipId?: true
  wizebotDebitTxId?: true
  wizebotCreditTxId?: true
  wizebotCreditError?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MarketBetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketBet to aggregate.
   */
  where?: Prisma.MarketBetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketBets to fetch.
   */
  orderBy?: Prisma.MarketBetOrderByWithRelationInput | Prisma.MarketBetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MarketBetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketBets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketBets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MarketBets
  **/
  _count?: true | MarketBetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MarketBetAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MarketBetSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MarketBetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MarketBetMaxAggregateInputType
}

export type GetMarketBetAggregateType<T extends MarketBetAggregateArgs> = {
      [P in keyof T & keyof AggregateMarketBet]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMarketBet[P]>
    : Prisma.GetScalarType<T[P], AggregateMarketBet[P]>
}




export type MarketBetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MarketBetWhereInput
  orderBy?: Prisma.MarketBetOrderByWithAggregationInput | Prisma.MarketBetOrderByWithAggregationInput[]
  by: Prisma.MarketBetScalarFieldEnum[] | Prisma.MarketBetScalarFieldEnum
  having?: Prisma.MarketBetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MarketBetCountAggregateInputType | true
  _avg?: MarketBetAvgAggregateInputType
  _sum?: MarketBetSumAggregateInputType
  _min?: MarketBetMinAggregateInputType
  _max?: MarketBetMaxAggregateInputType
}

export type MarketBetGroupByOutputType = {
  id: string
  marketId: string
  userId: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal
  source: $Enums.BetSource
  status: $Enums.BetStatus
  actualPayout: number
  settledAt: Date | null
  slipId: string | null
  wizebotDebitTxId: string | null
  wizebotCreditTxId: string | null
  wizebotCreditError: string | null
  createdAt: Date
  updatedAt: Date
  _count: MarketBetCountAggregateOutputType | null
  _avg: MarketBetAvgAggregateOutputType | null
  _sum: MarketBetSumAggregateOutputType | null
  _min: MarketBetMinAggregateOutputType | null
  _max: MarketBetMaxAggregateOutputType | null
}

export type GetMarketBetGroupByPayload<T extends MarketBetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MarketBetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MarketBetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MarketBetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MarketBetGroupByOutputType[P]>
      }
    >
  >



export type MarketBetWhereInput = {
  AND?: Prisma.MarketBetWhereInput | Prisma.MarketBetWhereInput[]
  OR?: Prisma.MarketBetWhereInput[]
  NOT?: Prisma.MarketBetWhereInput | Prisma.MarketBetWhereInput[]
  id?: Prisma.UuidFilter<"MarketBet"> | string
  marketId?: Prisma.UuidFilter<"MarketBet"> | string
  userId?: Prisma.UuidFilter<"MarketBet"> | string
  outcomeKey?: Prisma.StringFilter<"MarketBet"> | string
  pointsWagered?: Prisma.IntFilter<"MarketBet"> | number
  oddsAtPlacement?: Prisma.DecimalFilter<"MarketBet"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFilter<"MarketBet"> | $Enums.BetSource
  status?: Prisma.EnumBetStatusFilter<"MarketBet"> | $Enums.BetStatus
  actualPayout?: Prisma.IntFilter<"MarketBet"> | number
  settledAt?: Prisma.DateTimeNullableFilter<"MarketBet"> | Date | string | null
  slipId?: Prisma.UuidNullableFilter<"MarketBet"> | string | null
  wizebotDebitTxId?: Prisma.StringNullableFilter<"MarketBet"> | string | null
  wizebotCreditTxId?: Prisma.StringNullableFilter<"MarketBet"> | string | null
  wizebotCreditError?: Prisma.StringNullableFilter<"MarketBet"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MarketBet"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MarketBet"> | Date | string
  market?: Prisma.XOR<Prisma.BettingMarketScalarRelationFilter, Prisma.BettingMarketWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  slip?: Prisma.XOR<Prisma.BetSlipNullableScalarRelationFilter, Prisma.BetSlipWhereInput> | null
}

export type MarketBetOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  marketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  pointsWagered?: Prisma.SortOrder
  oddsAtPlacement?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPayout?: Prisma.SortOrder
  settledAt?: Prisma.SortOrderInput | Prisma.SortOrder
  slipId?: Prisma.SortOrderInput | Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  wizebotCreditTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  wizebotCreditError?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  market?: Prisma.BettingMarketOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  slip?: Prisma.BetSlipOrderByWithRelationInput
}

export type MarketBetWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MarketBetWhereInput | Prisma.MarketBetWhereInput[]
  OR?: Prisma.MarketBetWhereInput[]
  NOT?: Prisma.MarketBetWhereInput | Prisma.MarketBetWhereInput[]
  marketId?: Prisma.UuidFilter<"MarketBet"> | string
  userId?: Prisma.UuidFilter<"MarketBet"> | string
  outcomeKey?: Prisma.StringFilter<"MarketBet"> | string
  pointsWagered?: Prisma.IntFilter<"MarketBet"> | number
  oddsAtPlacement?: Prisma.DecimalFilter<"MarketBet"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFilter<"MarketBet"> | $Enums.BetSource
  status?: Prisma.EnumBetStatusFilter<"MarketBet"> | $Enums.BetStatus
  actualPayout?: Prisma.IntFilter<"MarketBet"> | number
  settledAt?: Prisma.DateTimeNullableFilter<"MarketBet"> | Date | string | null
  slipId?: Prisma.UuidNullableFilter<"MarketBet"> | string | null
  wizebotDebitTxId?: Prisma.StringNullableFilter<"MarketBet"> | string | null
  wizebotCreditTxId?: Prisma.StringNullableFilter<"MarketBet"> | string | null
  wizebotCreditError?: Prisma.StringNullableFilter<"MarketBet"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MarketBet"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MarketBet"> | Date | string
  market?: Prisma.XOR<Prisma.BettingMarketScalarRelationFilter, Prisma.BettingMarketWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  slip?: Prisma.XOR<Prisma.BetSlipNullableScalarRelationFilter, Prisma.BetSlipWhereInput> | null
}, "id">

export type MarketBetOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  marketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  pointsWagered?: Prisma.SortOrder
  oddsAtPlacement?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPayout?: Prisma.SortOrder
  settledAt?: Prisma.SortOrderInput | Prisma.SortOrder
  slipId?: Prisma.SortOrderInput | Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  wizebotCreditTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  wizebotCreditError?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MarketBetCountOrderByAggregateInput
  _avg?: Prisma.MarketBetAvgOrderByAggregateInput
  _max?: Prisma.MarketBetMaxOrderByAggregateInput
  _min?: Prisma.MarketBetMinOrderByAggregateInput
  _sum?: Prisma.MarketBetSumOrderByAggregateInput
}

export type MarketBetScalarWhereWithAggregatesInput = {
  AND?: Prisma.MarketBetScalarWhereWithAggregatesInput | Prisma.MarketBetScalarWhereWithAggregatesInput[]
  OR?: Prisma.MarketBetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MarketBetScalarWhereWithAggregatesInput | Prisma.MarketBetScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"MarketBet"> | string
  marketId?: Prisma.UuidWithAggregatesFilter<"MarketBet"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"MarketBet"> | string
  outcomeKey?: Prisma.StringWithAggregatesFilter<"MarketBet"> | string
  pointsWagered?: Prisma.IntWithAggregatesFilter<"MarketBet"> | number
  oddsAtPlacement?: Prisma.DecimalWithAggregatesFilter<"MarketBet"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceWithAggregatesFilter<"MarketBet"> | $Enums.BetSource
  status?: Prisma.EnumBetStatusWithAggregatesFilter<"MarketBet"> | $Enums.BetStatus
  actualPayout?: Prisma.IntWithAggregatesFilter<"MarketBet"> | number
  settledAt?: Prisma.DateTimeNullableWithAggregatesFilter<"MarketBet"> | Date | string | null
  slipId?: Prisma.UuidNullableWithAggregatesFilter<"MarketBet"> | string | null
  wizebotDebitTxId?: Prisma.StringNullableWithAggregatesFilter<"MarketBet"> | string | null
  wizebotCreditTxId?: Prisma.StringNullableWithAggregatesFilter<"MarketBet"> | string | null
  wizebotCreditError?: Prisma.StringNullableWithAggregatesFilter<"MarketBet"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MarketBet"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MarketBet"> | Date | string
}

export type MarketBetCreateInput = {
  id?: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  market: Prisma.BettingMarketCreateNestedOneWithoutBetsInput
  user: Prisma.UserCreateNestedOneWithoutMarketBetsInput
  slip?: Prisma.BetSlipCreateNestedOneWithoutBetsInput
}

export type MarketBetUncheckedCreateInput = {
  id?: string
  marketId: string
  userId: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  slipId?: string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketBetUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  market?: Prisma.BettingMarketUpdateOneRequiredWithoutBetsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutMarketBetsNestedInput
  slip?: Prisma.BetSlipUpdateOneWithoutBetsNestedInput
}

export type MarketBetUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  marketId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  slipId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketBetCreateManyInput = {
  id?: string
  marketId: string
  userId: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  slipId?: string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketBetUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketBetUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  marketId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  slipId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketBetListRelationFilter = {
  every?: Prisma.MarketBetWhereInput
  some?: Prisma.MarketBetWhereInput
  none?: Prisma.MarketBetWhereInput
}

export type MarketBetOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MarketBetCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  marketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  pointsWagered?: Prisma.SortOrder
  oddsAtPlacement?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPayout?: Prisma.SortOrder
  settledAt?: Prisma.SortOrder
  slipId?: Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrder
  wizebotCreditTxId?: Prisma.SortOrder
  wizebotCreditError?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MarketBetAvgOrderByAggregateInput = {
  pointsWagered?: Prisma.SortOrder
  oddsAtPlacement?: Prisma.SortOrder
  actualPayout?: Prisma.SortOrder
}

export type MarketBetMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  marketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  pointsWagered?: Prisma.SortOrder
  oddsAtPlacement?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPayout?: Prisma.SortOrder
  settledAt?: Prisma.SortOrder
  slipId?: Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrder
  wizebotCreditTxId?: Prisma.SortOrder
  wizebotCreditError?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MarketBetMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  marketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  outcomeKey?: Prisma.SortOrder
  pointsWagered?: Prisma.SortOrder
  oddsAtPlacement?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  actualPayout?: Prisma.SortOrder
  settledAt?: Prisma.SortOrder
  slipId?: Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrder
  wizebotCreditTxId?: Prisma.SortOrder
  wizebotCreditError?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MarketBetSumOrderByAggregateInput = {
  pointsWagered?: Prisma.SortOrder
  oddsAtPlacement?: Prisma.SortOrder
  actualPayout?: Prisma.SortOrder
}

export type MarketBetCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutUserInput, Prisma.MarketBetUncheckedCreateWithoutUserInput> | Prisma.MarketBetCreateWithoutUserInput[] | Prisma.MarketBetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutUserInput | Prisma.MarketBetCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MarketBetCreateManyUserInputEnvelope
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
}

export type MarketBetUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutUserInput, Prisma.MarketBetUncheckedCreateWithoutUserInput> | Prisma.MarketBetCreateWithoutUserInput[] | Prisma.MarketBetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutUserInput | Prisma.MarketBetCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MarketBetCreateManyUserInputEnvelope
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
}

export type MarketBetUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutUserInput, Prisma.MarketBetUncheckedCreateWithoutUserInput> | Prisma.MarketBetCreateWithoutUserInput[] | Prisma.MarketBetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutUserInput | Prisma.MarketBetCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MarketBetUpsertWithWhereUniqueWithoutUserInput | Prisma.MarketBetUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MarketBetCreateManyUserInputEnvelope
  set?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  disconnect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  delete?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  update?: Prisma.MarketBetUpdateWithWhereUniqueWithoutUserInput | Prisma.MarketBetUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MarketBetUpdateManyWithWhereWithoutUserInput | Prisma.MarketBetUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MarketBetScalarWhereInput | Prisma.MarketBetScalarWhereInput[]
}

export type MarketBetUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutUserInput, Prisma.MarketBetUncheckedCreateWithoutUserInput> | Prisma.MarketBetCreateWithoutUserInput[] | Prisma.MarketBetUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutUserInput | Prisma.MarketBetCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MarketBetUpsertWithWhereUniqueWithoutUserInput | Prisma.MarketBetUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MarketBetCreateManyUserInputEnvelope
  set?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  disconnect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  delete?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  update?: Prisma.MarketBetUpdateWithWhereUniqueWithoutUserInput | Prisma.MarketBetUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MarketBetUpdateManyWithWhereWithoutUserInput | Prisma.MarketBetUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MarketBetScalarWhereInput | Prisma.MarketBetScalarWhereInput[]
}

export type MarketBetCreateNestedManyWithoutMarketInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutMarketInput, Prisma.MarketBetUncheckedCreateWithoutMarketInput> | Prisma.MarketBetCreateWithoutMarketInput[] | Prisma.MarketBetUncheckedCreateWithoutMarketInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutMarketInput | Prisma.MarketBetCreateOrConnectWithoutMarketInput[]
  createMany?: Prisma.MarketBetCreateManyMarketInputEnvelope
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
}

export type MarketBetUncheckedCreateNestedManyWithoutMarketInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutMarketInput, Prisma.MarketBetUncheckedCreateWithoutMarketInput> | Prisma.MarketBetCreateWithoutMarketInput[] | Prisma.MarketBetUncheckedCreateWithoutMarketInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutMarketInput | Prisma.MarketBetCreateOrConnectWithoutMarketInput[]
  createMany?: Prisma.MarketBetCreateManyMarketInputEnvelope
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
}

export type MarketBetUpdateManyWithoutMarketNestedInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutMarketInput, Prisma.MarketBetUncheckedCreateWithoutMarketInput> | Prisma.MarketBetCreateWithoutMarketInput[] | Prisma.MarketBetUncheckedCreateWithoutMarketInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutMarketInput | Prisma.MarketBetCreateOrConnectWithoutMarketInput[]
  upsert?: Prisma.MarketBetUpsertWithWhereUniqueWithoutMarketInput | Prisma.MarketBetUpsertWithWhereUniqueWithoutMarketInput[]
  createMany?: Prisma.MarketBetCreateManyMarketInputEnvelope
  set?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  disconnect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  delete?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  update?: Prisma.MarketBetUpdateWithWhereUniqueWithoutMarketInput | Prisma.MarketBetUpdateWithWhereUniqueWithoutMarketInput[]
  updateMany?: Prisma.MarketBetUpdateManyWithWhereWithoutMarketInput | Prisma.MarketBetUpdateManyWithWhereWithoutMarketInput[]
  deleteMany?: Prisma.MarketBetScalarWhereInput | Prisma.MarketBetScalarWhereInput[]
}

export type MarketBetUncheckedUpdateManyWithoutMarketNestedInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutMarketInput, Prisma.MarketBetUncheckedCreateWithoutMarketInput> | Prisma.MarketBetCreateWithoutMarketInput[] | Prisma.MarketBetUncheckedCreateWithoutMarketInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutMarketInput | Prisma.MarketBetCreateOrConnectWithoutMarketInput[]
  upsert?: Prisma.MarketBetUpsertWithWhereUniqueWithoutMarketInput | Prisma.MarketBetUpsertWithWhereUniqueWithoutMarketInput[]
  createMany?: Prisma.MarketBetCreateManyMarketInputEnvelope
  set?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  disconnect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  delete?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  update?: Prisma.MarketBetUpdateWithWhereUniqueWithoutMarketInput | Prisma.MarketBetUpdateWithWhereUniqueWithoutMarketInput[]
  updateMany?: Prisma.MarketBetUpdateManyWithWhereWithoutMarketInput | Prisma.MarketBetUpdateManyWithWhereWithoutMarketInput[]
  deleteMany?: Prisma.MarketBetScalarWhereInput | Prisma.MarketBetScalarWhereInput[]
}

export type MarketBetCreateNestedManyWithoutSlipInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutSlipInput, Prisma.MarketBetUncheckedCreateWithoutSlipInput> | Prisma.MarketBetCreateWithoutSlipInput[] | Prisma.MarketBetUncheckedCreateWithoutSlipInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutSlipInput | Prisma.MarketBetCreateOrConnectWithoutSlipInput[]
  createMany?: Prisma.MarketBetCreateManySlipInputEnvelope
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
}

export type MarketBetUncheckedCreateNestedManyWithoutSlipInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutSlipInput, Prisma.MarketBetUncheckedCreateWithoutSlipInput> | Prisma.MarketBetCreateWithoutSlipInput[] | Prisma.MarketBetUncheckedCreateWithoutSlipInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutSlipInput | Prisma.MarketBetCreateOrConnectWithoutSlipInput[]
  createMany?: Prisma.MarketBetCreateManySlipInputEnvelope
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
}

export type MarketBetUpdateManyWithoutSlipNestedInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutSlipInput, Prisma.MarketBetUncheckedCreateWithoutSlipInput> | Prisma.MarketBetCreateWithoutSlipInput[] | Prisma.MarketBetUncheckedCreateWithoutSlipInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutSlipInput | Prisma.MarketBetCreateOrConnectWithoutSlipInput[]
  upsert?: Prisma.MarketBetUpsertWithWhereUniqueWithoutSlipInput | Prisma.MarketBetUpsertWithWhereUniqueWithoutSlipInput[]
  createMany?: Prisma.MarketBetCreateManySlipInputEnvelope
  set?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  disconnect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  delete?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  update?: Prisma.MarketBetUpdateWithWhereUniqueWithoutSlipInput | Prisma.MarketBetUpdateWithWhereUniqueWithoutSlipInput[]
  updateMany?: Prisma.MarketBetUpdateManyWithWhereWithoutSlipInput | Prisma.MarketBetUpdateManyWithWhereWithoutSlipInput[]
  deleteMany?: Prisma.MarketBetScalarWhereInput | Prisma.MarketBetScalarWhereInput[]
}

export type MarketBetUncheckedUpdateManyWithoutSlipNestedInput = {
  create?: Prisma.XOR<Prisma.MarketBetCreateWithoutSlipInput, Prisma.MarketBetUncheckedCreateWithoutSlipInput> | Prisma.MarketBetCreateWithoutSlipInput[] | Prisma.MarketBetUncheckedCreateWithoutSlipInput[]
  connectOrCreate?: Prisma.MarketBetCreateOrConnectWithoutSlipInput | Prisma.MarketBetCreateOrConnectWithoutSlipInput[]
  upsert?: Prisma.MarketBetUpsertWithWhereUniqueWithoutSlipInput | Prisma.MarketBetUpsertWithWhereUniqueWithoutSlipInput[]
  createMany?: Prisma.MarketBetCreateManySlipInputEnvelope
  set?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  disconnect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  delete?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  connect?: Prisma.MarketBetWhereUniqueInput | Prisma.MarketBetWhereUniqueInput[]
  update?: Prisma.MarketBetUpdateWithWhereUniqueWithoutSlipInput | Prisma.MarketBetUpdateWithWhereUniqueWithoutSlipInput[]
  updateMany?: Prisma.MarketBetUpdateManyWithWhereWithoutSlipInput | Prisma.MarketBetUpdateManyWithWhereWithoutSlipInput[]
  deleteMany?: Prisma.MarketBetScalarWhereInput | Prisma.MarketBetScalarWhereInput[]
}

export type MarketBetCreateWithoutUserInput = {
  id?: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  market: Prisma.BettingMarketCreateNestedOneWithoutBetsInput
  slip?: Prisma.BetSlipCreateNestedOneWithoutBetsInput
}

export type MarketBetUncheckedCreateWithoutUserInput = {
  id?: string
  marketId: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  slipId?: string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketBetCreateOrConnectWithoutUserInput = {
  where: Prisma.MarketBetWhereUniqueInput
  create: Prisma.XOR<Prisma.MarketBetCreateWithoutUserInput, Prisma.MarketBetUncheckedCreateWithoutUserInput>
}

export type MarketBetCreateManyUserInputEnvelope = {
  data: Prisma.MarketBetCreateManyUserInput | Prisma.MarketBetCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type MarketBetUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.MarketBetWhereUniqueInput
  update: Prisma.XOR<Prisma.MarketBetUpdateWithoutUserInput, Prisma.MarketBetUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.MarketBetCreateWithoutUserInput, Prisma.MarketBetUncheckedCreateWithoutUserInput>
}

export type MarketBetUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.MarketBetWhereUniqueInput
  data: Prisma.XOR<Prisma.MarketBetUpdateWithoutUserInput, Prisma.MarketBetUncheckedUpdateWithoutUserInput>
}

export type MarketBetUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.MarketBetScalarWhereInput
  data: Prisma.XOR<Prisma.MarketBetUpdateManyMutationInput, Prisma.MarketBetUncheckedUpdateManyWithoutUserInput>
}

export type MarketBetScalarWhereInput = {
  AND?: Prisma.MarketBetScalarWhereInput | Prisma.MarketBetScalarWhereInput[]
  OR?: Prisma.MarketBetScalarWhereInput[]
  NOT?: Prisma.MarketBetScalarWhereInput | Prisma.MarketBetScalarWhereInput[]
  id?: Prisma.UuidFilter<"MarketBet"> | string
  marketId?: Prisma.UuidFilter<"MarketBet"> | string
  userId?: Prisma.UuidFilter<"MarketBet"> | string
  outcomeKey?: Prisma.StringFilter<"MarketBet"> | string
  pointsWagered?: Prisma.IntFilter<"MarketBet"> | number
  oddsAtPlacement?: Prisma.DecimalFilter<"MarketBet"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFilter<"MarketBet"> | $Enums.BetSource
  status?: Prisma.EnumBetStatusFilter<"MarketBet"> | $Enums.BetStatus
  actualPayout?: Prisma.IntFilter<"MarketBet"> | number
  settledAt?: Prisma.DateTimeNullableFilter<"MarketBet"> | Date | string | null
  slipId?: Prisma.UuidNullableFilter<"MarketBet"> | string | null
  wizebotDebitTxId?: Prisma.StringNullableFilter<"MarketBet"> | string | null
  wizebotCreditTxId?: Prisma.StringNullableFilter<"MarketBet"> | string | null
  wizebotCreditError?: Prisma.StringNullableFilter<"MarketBet"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MarketBet"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MarketBet"> | Date | string
}

export type MarketBetCreateWithoutMarketInput = {
  id?: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutMarketBetsInput
  slip?: Prisma.BetSlipCreateNestedOneWithoutBetsInput
}

export type MarketBetUncheckedCreateWithoutMarketInput = {
  id?: string
  userId: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  slipId?: string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketBetCreateOrConnectWithoutMarketInput = {
  where: Prisma.MarketBetWhereUniqueInput
  create: Prisma.XOR<Prisma.MarketBetCreateWithoutMarketInput, Prisma.MarketBetUncheckedCreateWithoutMarketInput>
}

export type MarketBetCreateManyMarketInputEnvelope = {
  data: Prisma.MarketBetCreateManyMarketInput | Prisma.MarketBetCreateManyMarketInput[]
  skipDuplicates?: boolean
}

export type MarketBetUpsertWithWhereUniqueWithoutMarketInput = {
  where: Prisma.MarketBetWhereUniqueInput
  update: Prisma.XOR<Prisma.MarketBetUpdateWithoutMarketInput, Prisma.MarketBetUncheckedUpdateWithoutMarketInput>
  create: Prisma.XOR<Prisma.MarketBetCreateWithoutMarketInput, Prisma.MarketBetUncheckedCreateWithoutMarketInput>
}

export type MarketBetUpdateWithWhereUniqueWithoutMarketInput = {
  where: Prisma.MarketBetWhereUniqueInput
  data: Prisma.XOR<Prisma.MarketBetUpdateWithoutMarketInput, Prisma.MarketBetUncheckedUpdateWithoutMarketInput>
}

export type MarketBetUpdateManyWithWhereWithoutMarketInput = {
  where: Prisma.MarketBetScalarWhereInput
  data: Prisma.XOR<Prisma.MarketBetUpdateManyMutationInput, Prisma.MarketBetUncheckedUpdateManyWithoutMarketInput>
}

export type MarketBetCreateWithoutSlipInput = {
  id?: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  market: Prisma.BettingMarketCreateNestedOneWithoutBetsInput
  user: Prisma.UserCreateNestedOneWithoutMarketBetsInput
}

export type MarketBetUncheckedCreateWithoutSlipInput = {
  id?: string
  marketId: string
  userId: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketBetCreateOrConnectWithoutSlipInput = {
  where: Prisma.MarketBetWhereUniqueInput
  create: Prisma.XOR<Prisma.MarketBetCreateWithoutSlipInput, Prisma.MarketBetUncheckedCreateWithoutSlipInput>
}

export type MarketBetCreateManySlipInputEnvelope = {
  data: Prisma.MarketBetCreateManySlipInput | Prisma.MarketBetCreateManySlipInput[]
  skipDuplicates?: boolean
}

export type MarketBetUpsertWithWhereUniqueWithoutSlipInput = {
  where: Prisma.MarketBetWhereUniqueInput
  update: Prisma.XOR<Prisma.MarketBetUpdateWithoutSlipInput, Prisma.MarketBetUncheckedUpdateWithoutSlipInput>
  create: Prisma.XOR<Prisma.MarketBetCreateWithoutSlipInput, Prisma.MarketBetUncheckedCreateWithoutSlipInput>
}

export type MarketBetUpdateWithWhereUniqueWithoutSlipInput = {
  where: Prisma.MarketBetWhereUniqueInput
  data: Prisma.XOR<Prisma.MarketBetUpdateWithoutSlipInput, Prisma.MarketBetUncheckedUpdateWithoutSlipInput>
}

export type MarketBetUpdateManyWithWhereWithoutSlipInput = {
  where: Prisma.MarketBetScalarWhereInput
  data: Prisma.XOR<Prisma.MarketBetUpdateManyMutationInput, Prisma.MarketBetUncheckedUpdateManyWithoutSlipInput>
}

export type MarketBetCreateManyUserInput = {
  id?: string
  marketId: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  slipId?: string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketBetUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  market?: Prisma.BettingMarketUpdateOneRequiredWithoutBetsNestedInput
  slip?: Prisma.BetSlipUpdateOneWithoutBetsNestedInput
}

export type MarketBetUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  marketId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  slipId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketBetUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  marketId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  slipId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketBetCreateManyMarketInput = {
  id?: string
  userId: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  slipId?: string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketBetUpdateWithoutMarketInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutMarketBetsNestedInput
  slip?: Prisma.BetSlipUpdateOneWithoutBetsNestedInput
}

export type MarketBetUncheckedUpdateWithoutMarketInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  slipId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketBetUncheckedUpdateManyWithoutMarketInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  slipId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketBetCreateManySlipInput = {
  id?: string
  marketId: string
  userId: string
  outcomeKey: string
  pointsWagered: number
  oddsAtPlacement: runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: $Enums.BetSource
  status?: $Enums.BetStatus
  actualPayout?: number
  settledAt?: Date | string | null
  wizebotDebitTxId?: string | null
  wizebotCreditTxId?: string | null
  wizebotCreditError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketBetUpdateWithoutSlipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  market?: Prisma.BettingMarketUpdateOneRequiredWithoutBetsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutMarketBetsNestedInput
}

export type MarketBetUncheckedUpdateWithoutSlipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  marketId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketBetUncheckedUpdateManyWithoutSlipInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  marketId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  outcomeKey?: Prisma.StringFieldUpdateOperationsInput | string
  pointsWagered?: Prisma.IntFieldUpdateOperationsInput | number
  oddsAtPlacement?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  source?: Prisma.EnumBetSourceFieldUpdateOperationsInput | $Enums.BetSource
  status?: Prisma.EnumBetStatusFieldUpdateOperationsInput | $Enums.BetStatus
  actualPayout?: Prisma.IntFieldUpdateOperationsInput | number
  settledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wizebotCreditError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MarketBetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  marketId?: boolean
  userId?: boolean
  outcomeKey?: boolean
  pointsWagered?: boolean
  oddsAtPlacement?: boolean
  source?: boolean
  status?: boolean
  actualPayout?: boolean
  settledAt?: boolean
  slipId?: boolean
  wizebotDebitTxId?: boolean
  wizebotCreditTxId?: boolean
  wizebotCreditError?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  market?: boolean | Prisma.BettingMarketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  slip?: boolean | Prisma.MarketBet$slipArgs<ExtArgs>
}, ExtArgs["result"]["marketBet"]>

export type MarketBetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  marketId?: boolean
  userId?: boolean
  outcomeKey?: boolean
  pointsWagered?: boolean
  oddsAtPlacement?: boolean
  source?: boolean
  status?: boolean
  actualPayout?: boolean
  settledAt?: boolean
  slipId?: boolean
  wizebotDebitTxId?: boolean
  wizebotCreditTxId?: boolean
  wizebotCreditError?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  market?: boolean | Prisma.BettingMarketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  slip?: boolean | Prisma.MarketBet$slipArgs<ExtArgs>
}, ExtArgs["result"]["marketBet"]>

export type MarketBetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  marketId?: boolean
  userId?: boolean
  outcomeKey?: boolean
  pointsWagered?: boolean
  oddsAtPlacement?: boolean
  source?: boolean
  status?: boolean
  actualPayout?: boolean
  settledAt?: boolean
  slipId?: boolean
  wizebotDebitTxId?: boolean
  wizebotCreditTxId?: boolean
  wizebotCreditError?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  market?: boolean | Prisma.BettingMarketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  slip?: boolean | Prisma.MarketBet$slipArgs<ExtArgs>
}, ExtArgs["result"]["marketBet"]>

export type MarketBetSelectScalar = {
  id?: boolean
  marketId?: boolean
  userId?: boolean
  outcomeKey?: boolean
  pointsWagered?: boolean
  oddsAtPlacement?: boolean
  source?: boolean
  status?: boolean
  actualPayout?: boolean
  settledAt?: boolean
  slipId?: boolean
  wizebotDebitTxId?: boolean
  wizebotCreditTxId?: boolean
  wizebotCreditError?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MarketBetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "marketId" | "userId" | "outcomeKey" | "pointsWagered" | "oddsAtPlacement" | "source" | "status" | "actualPayout" | "settledAt" | "slipId" | "wizebotDebitTxId" | "wizebotCreditTxId" | "wizebotCreditError" | "createdAt" | "updatedAt", ExtArgs["result"]["marketBet"]>
export type MarketBetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  market?: boolean | Prisma.BettingMarketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  slip?: boolean | Prisma.MarketBet$slipArgs<ExtArgs>
}
export type MarketBetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  market?: boolean | Prisma.BettingMarketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  slip?: boolean | Prisma.MarketBet$slipArgs<ExtArgs>
}
export type MarketBetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  market?: boolean | Prisma.BettingMarketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  slip?: boolean | Prisma.MarketBet$slipArgs<ExtArgs>
}

export type $MarketBetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MarketBet"
  objects: {
    market: Prisma.$BettingMarketPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    slip: Prisma.$BetSlipPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    marketId: string
    userId: string
    outcomeKey: string
    pointsWagered: number
    oddsAtPlacement: runtime.Decimal
    source: $Enums.BetSource
    status: $Enums.BetStatus
    actualPayout: number
    settledAt: Date | null
    slipId: string | null
    wizebotDebitTxId: string | null
    wizebotCreditTxId: string | null
    wizebotCreditError: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["marketBet"]>
  composites: {}
}

export type MarketBetGetPayload<S extends boolean | null | undefined | MarketBetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MarketBetPayload, S>

export type MarketBetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MarketBetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MarketBetCountAggregateInputType | true
  }

export interface MarketBetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MarketBet'], meta: { name: 'MarketBet' } }
  /**
   * Find zero or one MarketBet that matches the filter.
   * @param {MarketBetFindUniqueArgs} args - Arguments to find a MarketBet
   * @example
   * // Get one MarketBet
   * const marketBet = await prisma.marketBet.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MarketBetFindUniqueArgs>(args: Prisma.SelectSubset<T, MarketBetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MarketBetClient<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MarketBet that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MarketBetFindUniqueOrThrowArgs} args - Arguments to find a MarketBet
   * @example
   * // Get one MarketBet
   * const marketBet = await prisma.marketBet.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MarketBetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MarketBetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketBetClient<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketBet that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketBetFindFirstArgs} args - Arguments to find a MarketBet
   * @example
   * // Get one MarketBet
   * const marketBet = await prisma.marketBet.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MarketBetFindFirstArgs>(args?: Prisma.SelectSubset<T, MarketBetFindFirstArgs<ExtArgs>>): Prisma.Prisma__MarketBetClient<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketBet that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketBetFindFirstOrThrowArgs} args - Arguments to find a MarketBet
   * @example
   * // Get one MarketBet
   * const marketBet = await prisma.marketBet.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MarketBetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MarketBetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketBetClient<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MarketBets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketBetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MarketBets
   * const marketBets = await prisma.marketBet.findMany()
   * 
   * // Get first 10 MarketBets
   * const marketBets = await prisma.marketBet.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const marketBetWithIdOnly = await prisma.marketBet.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MarketBetFindManyArgs>(args?: Prisma.SelectSubset<T, MarketBetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MarketBet.
   * @param {MarketBetCreateArgs} args - Arguments to create a MarketBet.
   * @example
   * // Create one MarketBet
   * const MarketBet = await prisma.marketBet.create({
   *   data: {
   *     // ... data to create a MarketBet
   *   }
   * })
   * 
   */
  create<T extends MarketBetCreateArgs>(args: Prisma.SelectSubset<T, MarketBetCreateArgs<ExtArgs>>): Prisma.Prisma__MarketBetClient<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MarketBets.
   * @param {MarketBetCreateManyArgs} args - Arguments to create many MarketBets.
   * @example
   * // Create many MarketBets
   * const marketBet = await prisma.marketBet.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MarketBetCreateManyArgs>(args?: Prisma.SelectSubset<T, MarketBetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MarketBets and returns the data saved in the database.
   * @param {MarketBetCreateManyAndReturnArgs} args - Arguments to create many MarketBets.
   * @example
   * // Create many MarketBets
   * const marketBet = await prisma.marketBet.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MarketBets and only return the `id`
   * const marketBetWithIdOnly = await prisma.marketBet.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MarketBetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MarketBetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MarketBet.
   * @param {MarketBetDeleteArgs} args - Arguments to delete one MarketBet.
   * @example
   * // Delete one MarketBet
   * const MarketBet = await prisma.marketBet.delete({
   *   where: {
   *     // ... filter to delete one MarketBet
   *   }
   * })
   * 
   */
  delete<T extends MarketBetDeleteArgs>(args: Prisma.SelectSubset<T, MarketBetDeleteArgs<ExtArgs>>): Prisma.Prisma__MarketBetClient<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MarketBet.
   * @param {MarketBetUpdateArgs} args - Arguments to update one MarketBet.
   * @example
   * // Update one MarketBet
   * const marketBet = await prisma.marketBet.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MarketBetUpdateArgs>(args: Prisma.SelectSubset<T, MarketBetUpdateArgs<ExtArgs>>): Prisma.Prisma__MarketBetClient<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MarketBets.
   * @param {MarketBetDeleteManyArgs} args - Arguments to filter MarketBets to delete.
   * @example
   * // Delete a few MarketBets
   * const { count } = await prisma.marketBet.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MarketBetDeleteManyArgs>(args?: Prisma.SelectSubset<T, MarketBetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketBets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketBetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MarketBets
   * const marketBet = await prisma.marketBet.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MarketBetUpdateManyArgs>(args: Prisma.SelectSubset<T, MarketBetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketBets and returns the data updated in the database.
   * @param {MarketBetUpdateManyAndReturnArgs} args - Arguments to update many MarketBets.
   * @example
   * // Update many MarketBets
   * const marketBet = await prisma.marketBet.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MarketBets and only return the `id`
   * const marketBetWithIdOnly = await prisma.marketBet.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MarketBetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MarketBetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MarketBet.
   * @param {MarketBetUpsertArgs} args - Arguments to update or create a MarketBet.
   * @example
   * // Update or create a MarketBet
   * const marketBet = await prisma.marketBet.upsert({
   *   create: {
   *     // ... data to create a MarketBet
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MarketBet we want to update
   *   }
   * })
   */
  upsert<T extends MarketBetUpsertArgs>(args: Prisma.SelectSubset<T, MarketBetUpsertArgs<ExtArgs>>): Prisma.Prisma__MarketBetClient<runtime.Types.Result.GetResult<Prisma.$MarketBetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MarketBets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketBetCountArgs} args - Arguments to filter MarketBets to count.
   * @example
   * // Count the number of MarketBets
   * const count = await prisma.marketBet.count({
   *   where: {
   *     // ... the filter for the MarketBets we want to count
   *   }
   * })
  **/
  count<T extends MarketBetCountArgs>(
    args?: Prisma.Subset<T, MarketBetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MarketBetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MarketBet.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketBetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MarketBetAggregateArgs>(args: Prisma.Subset<T, MarketBetAggregateArgs>): Prisma.PrismaPromise<GetMarketBetAggregateType<T>>

  /**
   * Group by MarketBet.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketBetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MarketBetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MarketBetGroupByArgs['orderBy'] }
      : { orderBy?: MarketBetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MarketBetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMarketBetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MarketBet model
 */
readonly fields: MarketBetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MarketBet.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MarketBetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  market<T extends Prisma.BettingMarketDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BettingMarketDefaultArgs<ExtArgs>>): Prisma.Prisma__BettingMarketClient<runtime.Types.Result.GetResult<Prisma.$BettingMarketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  slip<T extends Prisma.MarketBet$slipArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MarketBet$slipArgs<ExtArgs>>): Prisma.Prisma__BetSlipClient<runtime.Types.Result.GetResult<Prisma.$BetSlipPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MarketBet model
 */
export interface MarketBetFieldRefs {
  readonly id: Prisma.FieldRef<"MarketBet", 'String'>
  readonly marketId: Prisma.FieldRef<"MarketBet", 'String'>
  readonly userId: Prisma.FieldRef<"MarketBet", 'String'>
  readonly outcomeKey: Prisma.FieldRef<"MarketBet", 'String'>
  readonly pointsWagered: Prisma.FieldRef<"MarketBet", 'Int'>
  readonly oddsAtPlacement: Prisma.FieldRef<"MarketBet", 'Decimal'>
  readonly source: Prisma.FieldRef<"MarketBet", 'BetSource'>
  readonly status: Prisma.FieldRef<"MarketBet", 'BetStatus'>
  readonly actualPayout: Prisma.FieldRef<"MarketBet", 'Int'>
  readonly settledAt: Prisma.FieldRef<"MarketBet", 'DateTime'>
  readonly slipId: Prisma.FieldRef<"MarketBet", 'String'>
  readonly wizebotDebitTxId: Prisma.FieldRef<"MarketBet", 'String'>
  readonly wizebotCreditTxId: Prisma.FieldRef<"MarketBet", 'String'>
  readonly wizebotCreditError: Prisma.FieldRef<"MarketBet", 'String'>
  readonly createdAt: Prisma.FieldRef<"MarketBet", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MarketBet", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MarketBet findUnique
 */
export type MarketBetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
  /**
   * Filter, which MarketBet to fetch.
   */
  where: Prisma.MarketBetWhereUniqueInput
}

/**
 * MarketBet findUniqueOrThrow
 */
export type MarketBetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
  /**
   * Filter, which MarketBet to fetch.
   */
  where: Prisma.MarketBetWhereUniqueInput
}

/**
 * MarketBet findFirst
 */
export type MarketBetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
  /**
   * Filter, which MarketBet to fetch.
   */
  where?: Prisma.MarketBetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketBets to fetch.
   */
  orderBy?: Prisma.MarketBetOrderByWithRelationInput | Prisma.MarketBetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketBets.
   */
  cursor?: Prisma.MarketBetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketBets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketBets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketBets.
   */
  distinct?: Prisma.MarketBetScalarFieldEnum | Prisma.MarketBetScalarFieldEnum[]
}

/**
 * MarketBet findFirstOrThrow
 */
export type MarketBetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
  /**
   * Filter, which MarketBet to fetch.
   */
  where?: Prisma.MarketBetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketBets to fetch.
   */
  orderBy?: Prisma.MarketBetOrderByWithRelationInput | Prisma.MarketBetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketBets.
   */
  cursor?: Prisma.MarketBetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketBets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketBets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketBets.
   */
  distinct?: Prisma.MarketBetScalarFieldEnum | Prisma.MarketBetScalarFieldEnum[]
}

/**
 * MarketBet findMany
 */
export type MarketBetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
  /**
   * Filter, which MarketBets to fetch.
   */
  where?: Prisma.MarketBetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketBets to fetch.
   */
  orderBy?: Prisma.MarketBetOrderByWithRelationInput | Prisma.MarketBetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MarketBets.
   */
  cursor?: Prisma.MarketBetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketBets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketBets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketBets.
   */
  distinct?: Prisma.MarketBetScalarFieldEnum | Prisma.MarketBetScalarFieldEnum[]
}

/**
 * MarketBet create
 */
export type MarketBetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
  /**
   * The data needed to create a MarketBet.
   */
  data: Prisma.XOR<Prisma.MarketBetCreateInput, Prisma.MarketBetUncheckedCreateInput>
}

/**
 * MarketBet createMany
 */
export type MarketBetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MarketBets.
   */
  data: Prisma.MarketBetCreateManyInput | Prisma.MarketBetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MarketBet createManyAndReturn
 */
export type MarketBetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * The data used to create many MarketBets.
   */
  data: Prisma.MarketBetCreateManyInput | Prisma.MarketBetCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MarketBet update
 */
export type MarketBetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
  /**
   * The data needed to update a MarketBet.
   */
  data: Prisma.XOR<Prisma.MarketBetUpdateInput, Prisma.MarketBetUncheckedUpdateInput>
  /**
   * Choose, which MarketBet to update.
   */
  where: Prisma.MarketBetWhereUniqueInput
}

/**
 * MarketBet updateMany
 */
export type MarketBetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MarketBets.
   */
  data: Prisma.XOR<Prisma.MarketBetUpdateManyMutationInput, Prisma.MarketBetUncheckedUpdateManyInput>
  /**
   * Filter which MarketBets to update
   */
  where?: Prisma.MarketBetWhereInput
  /**
   * Limit how many MarketBets to update.
   */
  limit?: number
}

/**
 * MarketBet updateManyAndReturn
 */
export type MarketBetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * The data used to update MarketBets.
   */
  data: Prisma.XOR<Prisma.MarketBetUpdateManyMutationInput, Prisma.MarketBetUncheckedUpdateManyInput>
  /**
   * Filter which MarketBets to update
   */
  where?: Prisma.MarketBetWhereInput
  /**
   * Limit how many MarketBets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MarketBet upsert
 */
export type MarketBetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
  /**
   * The filter to search for the MarketBet to update in case it exists.
   */
  where: Prisma.MarketBetWhereUniqueInput
  /**
   * In case the MarketBet found by the `where` argument doesn't exist, create a new MarketBet with this data.
   */
  create: Prisma.XOR<Prisma.MarketBetCreateInput, Prisma.MarketBetUncheckedCreateInput>
  /**
   * In case the MarketBet was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MarketBetUpdateInput, Prisma.MarketBetUncheckedUpdateInput>
}

/**
 * MarketBet delete
 */
export type MarketBetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
  /**
   * Filter which MarketBet to delete.
   */
  where: Prisma.MarketBetWhereUniqueInput
}

/**
 * MarketBet deleteMany
 */
export type MarketBetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketBets to delete
   */
  where?: Prisma.MarketBetWhereInput
  /**
   * Limit how many MarketBets to delete.
   */
  limit?: number
}

/**
 * MarketBet.slip
 */
export type MarketBet$slipArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BetSlip
   */
  select?: Prisma.BetSlipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BetSlip
   */
  omit?: Prisma.BetSlipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BetSlipInclude<ExtArgs> | null
  where?: Prisma.BetSlipWhereInput
}

/**
 * MarketBet without action
 */
export type MarketBetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketBet
   */
  select?: Prisma.MarketBetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketBet
   */
  omit?: Prisma.MarketBetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MarketBetInclude<ExtArgs> | null
}
