
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MatchPlayerStats` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model MatchPlayerStats
 * 
 */
export type MatchPlayerStatsModel = runtime.Types.Result.DefaultSelection<Prisma.$MatchPlayerStatsPayload>

export type AggregateMatchPlayerStats = {
  _count: MatchPlayerStatsCountAggregateOutputType | null
  _avg: MatchPlayerStatsAvgAggregateOutputType | null
  _sum: MatchPlayerStatsSumAggregateOutputType | null
  _min: MatchPlayerStatsMinAggregateOutputType | null
  _max: MatchPlayerStatsMaxAggregateOutputType | null
}

export type MatchPlayerStatsAvgAggregateOutputType = {
  goals: number | null
  assists: number | null
  yellowCards: number | null
  redCards: number | null
}

export type MatchPlayerStatsSumAggregateOutputType = {
  goals: number | null
  assists: number | null
  yellowCards: number | null
  redCards: number | null
}

export type MatchPlayerStatsMinAggregateOutputType = {
  id: string | null
  goals: number | null
  assists: number | null
  yellowCards: number | null
  redCards: number | null
  matchId: string | null
  playerId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MatchPlayerStatsMaxAggregateOutputType = {
  id: string | null
  goals: number | null
  assists: number | null
  yellowCards: number | null
  redCards: number | null
  matchId: string | null
  playerId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MatchPlayerStatsCountAggregateOutputType = {
  id: number
  goals: number
  assists: number
  yellowCards: number
  redCards: number
  matchId: number
  playerId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MatchPlayerStatsAvgAggregateInputType = {
  goals?: true
  assists?: true
  yellowCards?: true
  redCards?: true
}

export type MatchPlayerStatsSumAggregateInputType = {
  goals?: true
  assists?: true
  yellowCards?: true
  redCards?: true
}

export type MatchPlayerStatsMinAggregateInputType = {
  id?: true
  goals?: true
  assists?: true
  yellowCards?: true
  redCards?: true
  matchId?: true
  playerId?: true
  createdAt?: true
  updatedAt?: true
}

export type MatchPlayerStatsMaxAggregateInputType = {
  id?: true
  goals?: true
  assists?: true
  yellowCards?: true
  redCards?: true
  matchId?: true
  playerId?: true
  createdAt?: true
  updatedAt?: true
}

export type MatchPlayerStatsCountAggregateInputType = {
  id?: true
  goals?: true
  assists?: true
  yellowCards?: true
  redCards?: true
  matchId?: true
  playerId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MatchPlayerStatsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MatchPlayerStats to aggregate.
   */
  where?: Prisma.MatchPlayerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MatchPlayerStats to fetch.
   */
  orderBy?: Prisma.MatchPlayerStatsOrderByWithRelationInput | Prisma.MatchPlayerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MatchPlayerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MatchPlayerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MatchPlayerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MatchPlayerStats
  **/
  _count?: true | MatchPlayerStatsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MatchPlayerStatsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MatchPlayerStatsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MatchPlayerStatsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MatchPlayerStatsMaxAggregateInputType
}

export type GetMatchPlayerStatsAggregateType<T extends MatchPlayerStatsAggregateArgs> = {
      [P in keyof T & keyof AggregateMatchPlayerStats]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMatchPlayerStats[P]>
    : Prisma.GetScalarType<T[P], AggregateMatchPlayerStats[P]>
}




export type MatchPlayerStatsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MatchPlayerStatsWhereInput
  orderBy?: Prisma.MatchPlayerStatsOrderByWithAggregationInput | Prisma.MatchPlayerStatsOrderByWithAggregationInput[]
  by: Prisma.MatchPlayerStatsScalarFieldEnum[] | Prisma.MatchPlayerStatsScalarFieldEnum
  having?: Prisma.MatchPlayerStatsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MatchPlayerStatsCountAggregateInputType | true
  _avg?: MatchPlayerStatsAvgAggregateInputType
  _sum?: MatchPlayerStatsSumAggregateInputType
  _min?: MatchPlayerStatsMinAggregateInputType
  _max?: MatchPlayerStatsMaxAggregateInputType
}

export type MatchPlayerStatsGroupByOutputType = {
  id: string
  goals: number
  assists: number
  yellowCards: number
  redCards: number
  matchId: string
  playerId: string
  createdAt: Date
  updatedAt: Date
  _count: MatchPlayerStatsCountAggregateOutputType | null
  _avg: MatchPlayerStatsAvgAggregateOutputType | null
  _sum: MatchPlayerStatsSumAggregateOutputType | null
  _min: MatchPlayerStatsMinAggregateOutputType | null
  _max: MatchPlayerStatsMaxAggregateOutputType | null
}

export type GetMatchPlayerStatsGroupByPayload<T extends MatchPlayerStatsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MatchPlayerStatsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MatchPlayerStatsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MatchPlayerStatsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MatchPlayerStatsGroupByOutputType[P]>
      }
    >
  >



export type MatchPlayerStatsWhereInput = {
  AND?: Prisma.MatchPlayerStatsWhereInput | Prisma.MatchPlayerStatsWhereInput[]
  OR?: Prisma.MatchPlayerStatsWhereInput[]
  NOT?: Prisma.MatchPlayerStatsWhereInput | Prisma.MatchPlayerStatsWhereInput[]
  id?: Prisma.UuidFilter<"MatchPlayerStats"> | string
  goals?: Prisma.IntFilter<"MatchPlayerStats"> | number
  assists?: Prisma.IntFilter<"MatchPlayerStats"> | number
  yellowCards?: Prisma.IntFilter<"MatchPlayerStats"> | number
  redCards?: Prisma.IntFilter<"MatchPlayerStats"> | number
  matchId?: Prisma.UuidFilter<"MatchPlayerStats"> | string
  playerId?: Prisma.UuidFilter<"MatchPlayerStats"> | string
  createdAt?: Prisma.DateTimeFilter<"MatchPlayerStats"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MatchPlayerStats"> | Date | string
  match?: Prisma.XOR<Prisma.MatchScalarRelationFilter, Prisma.MatchWhereInput>
  player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
}

export type MatchPlayerStatsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  goals?: Prisma.SortOrder
  assists?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  matchId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  match?: Prisma.MatchOrderByWithRelationInput
  player?: Prisma.PlayerOrderByWithRelationInput
}

export type MatchPlayerStatsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  matchId_playerId?: Prisma.MatchPlayerStatsMatchIdPlayerIdCompoundUniqueInput
  AND?: Prisma.MatchPlayerStatsWhereInput | Prisma.MatchPlayerStatsWhereInput[]
  OR?: Prisma.MatchPlayerStatsWhereInput[]
  NOT?: Prisma.MatchPlayerStatsWhereInput | Prisma.MatchPlayerStatsWhereInput[]
  goals?: Prisma.IntFilter<"MatchPlayerStats"> | number
  assists?: Prisma.IntFilter<"MatchPlayerStats"> | number
  yellowCards?: Prisma.IntFilter<"MatchPlayerStats"> | number
  redCards?: Prisma.IntFilter<"MatchPlayerStats"> | number
  matchId?: Prisma.UuidFilter<"MatchPlayerStats"> | string
  playerId?: Prisma.UuidFilter<"MatchPlayerStats"> | string
  createdAt?: Prisma.DateTimeFilter<"MatchPlayerStats"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MatchPlayerStats"> | Date | string
  match?: Prisma.XOR<Prisma.MatchScalarRelationFilter, Prisma.MatchWhereInput>
  player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
}, "id" | "matchId_playerId">

export type MatchPlayerStatsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  goals?: Prisma.SortOrder
  assists?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  matchId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MatchPlayerStatsCountOrderByAggregateInput
  _avg?: Prisma.MatchPlayerStatsAvgOrderByAggregateInput
  _max?: Prisma.MatchPlayerStatsMaxOrderByAggregateInput
  _min?: Prisma.MatchPlayerStatsMinOrderByAggregateInput
  _sum?: Prisma.MatchPlayerStatsSumOrderByAggregateInput
}

export type MatchPlayerStatsScalarWhereWithAggregatesInput = {
  AND?: Prisma.MatchPlayerStatsScalarWhereWithAggregatesInput | Prisma.MatchPlayerStatsScalarWhereWithAggregatesInput[]
  OR?: Prisma.MatchPlayerStatsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MatchPlayerStatsScalarWhereWithAggregatesInput | Prisma.MatchPlayerStatsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"MatchPlayerStats"> | string
  goals?: Prisma.IntWithAggregatesFilter<"MatchPlayerStats"> | number
  assists?: Prisma.IntWithAggregatesFilter<"MatchPlayerStats"> | number
  yellowCards?: Prisma.IntWithAggregatesFilter<"MatchPlayerStats"> | number
  redCards?: Prisma.IntWithAggregatesFilter<"MatchPlayerStats"> | number
  matchId?: Prisma.UuidWithAggregatesFilter<"MatchPlayerStats"> | string
  playerId?: Prisma.UuidWithAggregatesFilter<"MatchPlayerStats"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MatchPlayerStats"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MatchPlayerStats"> | Date | string
}

export type MatchPlayerStatsCreateInput = {
  id?: string
  goals?: number
  assists?: number
  yellowCards?: number
  redCards?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  match: Prisma.MatchCreateNestedOneWithoutPlayerStatsInput
  player: Prisma.PlayerCreateNestedOneWithoutStatsInput
}

export type MatchPlayerStatsUncheckedCreateInput = {
  id?: string
  goals?: number
  assists?: number
  yellowCards?: number
  redCards?: number
  matchId: string
  playerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MatchPlayerStatsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  match?: Prisma.MatchUpdateOneRequiredWithoutPlayerStatsNestedInput
  player?: Prisma.PlayerUpdateOneRequiredWithoutStatsNestedInput
}

export type MatchPlayerStatsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  matchId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MatchPlayerStatsCreateManyInput = {
  id?: string
  goals?: number
  assists?: number
  yellowCards?: number
  redCards?: number
  matchId: string
  playerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MatchPlayerStatsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MatchPlayerStatsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  matchId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MatchPlayerStatsListRelationFilter = {
  every?: Prisma.MatchPlayerStatsWhereInput
  some?: Prisma.MatchPlayerStatsWhereInput
  none?: Prisma.MatchPlayerStatsWhereInput
}

export type MatchPlayerStatsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MatchPlayerStatsMatchIdPlayerIdCompoundUniqueInput = {
  matchId: string
  playerId: string
}

export type MatchPlayerStatsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  goals?: Prisma.SortOrder
  assists?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  matchId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MatchPlayerStatsAvgOrderByAggregateInput = {
  goals?: Prisma.SortOrder
  assists?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
}

export type MatchPlayerStatsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  goals?: Prisma.SortOrder
  assists?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  matchId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MatchPlayerStatsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  goals?: Prisma.SortOrder
  assists?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  matchId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MatchPlayerStatsSumOrderByAggregateInput = {
  goals?: Prisma.SortOrder
  assists?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
}

export type MatchPlayerStatsCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutPlayerInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput> | Prisma.MatchPlayerStatsCreateWithoutPlayerInput[] | Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.MatchPlayerStatsCreateOrConnectWithoutPlayerInput | Prisma.MatchPlayerStatsCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.MatchPlayerStatsCreateManyPlayerInputEnvelope
  connect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
}

export type MatchPlayerStatsUncheckedCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutPlayerInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput> | Prisma.MatchPlayerStatsCreateWithoutPlayerInput[] | Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.MatchPlayerStatsCreateOrConnectWithoutPlayerInput | Prisma.MatchPlayerStatsCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.MatchPlayerStatsCreateManyPlayerInputEnvelope
  connect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
}

export type MatchPlayerStatsUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutPlayerInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput> | Prisma.MatchPlayerStatsCreateWithoutPlayerInput[] | Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.MatchPlayerStatsCreateOrConnectWithoutPlayerInput | Prisma.MatchPlayerStatsCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.MatchPlayerStatsUpsertWithWhereUniqueWithoutPlayerInput | Prisma.MatchPlayerStatsUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.MatchPlayerStatsCreateManyPlayerInputEnvelope
  set?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  disconnect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  delete?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  connect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  update?: Prisma.MatchPlayerStatsUpdateWithWhereUniqueWithoutPlayerInput | Prisma.MatchPlayerStatsUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.MatchPlayerStatsUpdateManyWithWhereWithoutPlayerInput | Prisma.MatchPlayerStatsUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.MatchPlayerStatsScalarWhereInput | Prisma.MatchPlayerStatsScalarWhereInput[]
}

export type MatchPlayerStatsUncheckedUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutPlayerInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput> | Prisma.MatchPlayerStatsCreateWithoutPlayerInput[] | Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.MatchPlayerStatsCreateOrConnectWithoutPlayerInput | Prisma.MatchPlayerStatsCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.MatchPlayerStatsUpsertWithWhereUniqueWithoutPlayerInput | Prisma.MatchPlayerStatsUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.MatchPlayerStatsCreateManyPlayerInputEnvelope
  set?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  disconnect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  delete?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  connect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  update?: Prisma.MatchPlayerStatsUpdateWithWhereUniqueWithoutPlayerInput | Prisma.MatchPlayerStatsUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.MatchPlayerStatsUpdateManyWithWhereWithoutPlayerInput | Prisma.MatchPlayerStatsUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.MatchPlayerStatsScalarWhereInput | Prisma.MatchPlayerStatsScalarWhereInput[]
}

export type MatchPlayerStatsCreateNestedManyWithoutMatchInput = {
  create?: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutMatchInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput> | Prisma.MatchPlayerStatsCreateWithoutMatchInput[] | Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput[]
  connectOrCreate?: Prisma.MatchPlayerStatsCreateOrConnectWithoutMatchInput | Prisma.MatchPlayerStatsCreateOrConnectWithoutMatchInput[]
  createMany?: Prisma.MatchPlayerStatsCreateManyMatchInputEnvelope
  connect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
}

export type MatchPlayerStatsUncheckedCreateNestedManyWithoutMatchInput = {
  create?: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutMatchInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput> | Prisma.MatchPlayerStatsCreateWithoutMatchInput[] | Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput[]
  connectOrCreate?: Prisma.MatchPlayerStatsCreateOrConnectWithoutMatchInput | Prisma.MatchPlayerStatsCreateOrConnectWithoutMatchInput[]
  createMany?: Prisma.MatchPlayerStatsCreateManyMatchInputEnvelope
  connect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
}

export type MatchPlayerStatsUpdateManyWithoutMatchNestedInput = {
  create?: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutMatchInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput> | Prisma.MatchPlayerStatsCreateWithoutMatchInput[] | Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput[]
  connectOrCreate?: Prisma.MatchPlayerStatsCreateOrConnectWithoutMatchInput | Prisma.MatchPlayerStatsCreateOrConnectWithoutMatchInput[]
  upsert?: Prisma.MatchPlayerStatsUpsertWithWhereUniqueWithoutMatchInput | Prisma.MatchPlayerStatsUpsertWithWhereUniqueWithoutMatchInput[]
  createMany?: Prisma.MatchPlayerStatsCreateManyMatchInputEnvelope
  set?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  disconnect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  delete?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  connect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  update?: Prisma.MatchPlayerStatsUpdateWithWhereUniqueWithoutMatchInput | Prisma.MatchPlayerStatsUpdateWithWhereUniqueWithoutMatchInput[]
  updateMany?: Prisma.MatchPlayerStatsUpdateManyWithWhereWithoutMatchInput | Prisma.MatchPlayerStatsUpdateManyWithWhereWithoutMatchInput[]
  deleteMany?: Prisma.MatchPlayerStatsScalarWhereInput | Prisma.MatchPlayerStatsScalarWhereInput[]
}

export type MatchPlayerStatsUncheckedUpdateManyWithoutMatchNestedInput = {
  create?: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutMatchInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput> | Prisma.MatchPlayerStatsCreateWithoutMatchInput[] | Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput[]
  connectOrCreate?: Prisma.MatchPlayerStatsCreateOrConnectWithoutMatchInput | Prisma.MatchPlayerStatsCreateOrConnectWithoutMatchInput[]
  upsert?: Prisma.MatchPlayerStatsUpsertWithWhereUniqueWithoutMatchInput | Prisma.MatchPlayerStatsUpsertWithWhereUniqueWithoutMatchInput[]
  createMany?: Prisma.MatchPlayerStatsCreateManyMatchInputEnvelope
  set?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  disconnect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  delete?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  connect?: Prisma.MatchPlayerStatsWhereUniqueInput | Prisma.MatchPlayerStatsWhereUniqueInput[]
  update?: Prisma.MatchPlayerStatsUpdateWithWhereUniqueWithoutMatchInput | Prisma.MatchPlayerStatsUpdateWithWhereUniqueWithoutMatchInput[]
  updateMany?: Prisma.MatchPlayerStatsUpdateManyWithWhereWithoutMatchInput | Prisma.MatchPlayerStatsUpdateManyWithWhereWithoutMatchInput[]
  deleteMany?: Prisma.MatchPlayerStatsScalarWhereInput | Prisma.MatchPlayerStatsScalarWhereInput[]
}

export type MatchPlayerStatsCreateWithoutPlayerInput = {
  id?: string
  goals?: number
  assists?: number
  yellowCards?: number
  redCards?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  match: Prisma.MatchCreateNestedOneWithoutPlayerStatsInput
}

export type MatchPlayerStatsUncheckedCreateWithoutPlayerInput = {
  id?: string
  goals?: number
  assists?: number
  yellowCards?: number
  redCards?: number
  matchId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MatchPlayerStatsCreateOrConnectWithoutPlayerInput = {
  where: Prisma.MatchPlayerStatsWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutPlayerInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput>
}

export type MatchPlayerStatsCreateManyPlayerInputEnvelope = {
  data: Prisma.MatchPlayerStatsCreateManyPlayerInput | Prisma.MatchPlayerStatsCreateManyPlayerInput[]
  skipDuplicates?: boolean
}

export type MatchPlayerStatsUpsertWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.MatchPlayerStatsWhereUniqueInput
  update: Prisma.XOR<Prisma.MatchPlayerStatsUpdateWithoutPlayerInput, Prisma.MatchPlayerStatsUncheckedUpdateWithoutPlayerInput>
  create: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutPlayerInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutPlayerInput>
}

export type MatchPlayerStatsUpdateWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.MatchPlayerStatsWhereUniqueInput
  data: Prisma.XOR<Prisma.MatchPlayerStatsUpdateWithoutPlayerInput, Prisma.MatchPlayerStatsUncheckedUpdateWithoutPlayerInput>
}

export type MatchPlayerStatsUpdateManyWithWhereWithoutPlayerInput = {
  where: Prisma.MatchPlayerStatsScalarWhereInput
  data: Prisma.XOR<Prisma.MatchPlayerStatsUpdateManyMutationInput, Prisma.MatchPlayerStatsUncheckedUpdateManyWithoutPlayerInput>
}

export type MatchPlayerStatsScalarWhereInput = {
  AND?: Prisma.MatchPlayerStatsScalarWhereInput | Prisma.MatchPlayerStatsScalarWhereInput[]
  OR?: Prisma.MatchPlayerStatsScalarWhereInput[]
  NOT?: Prisma.MatchPlayerStatsScalarWhereInput | Prisma.MatchPlayerStatsScalarWhereInput[]
  id?: Prisma.UuidFilter<"MatchPlayerStats"> | string
  goals?: Prisma.IntFilter<"MatchPlayerStats"> | number
  assists?: Prisma.IntFilter<"MatchPlayerStats"> | number
  yellowCards?: Prisma.IntFilter<"MatchPlayerStats"> | number
  redCards?: Prisma.IntFilter<"MatchPlayerStats"> | number
  matchId?: Prisma.UuidFilter<"MatchPlayerStats"> | string
  playerId?: Prisma.UuidFilter<"MatchPlayerStats"> | string
  createdAt?: Prisma.DateTimeFilter<"MatchPlayerStats"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MatchPlayerStats"> | Date | string
}

export type MatchPlayerStatsCreateWithoutMatchInput = {
  id?: string
  goals?: number
  assists?: number
  yellowCards?: number
  redCards?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  player: Prisma.PlayerCreateNestedOneWithoutStatsInput
}

export type MatchPlayerStatsUncheckedCreateWithoutMatchInput = {
  id?: string
  goals?: number
  assists?: number
  yellowCards?: number
  redCards?: number
  playerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MatchPlayerStatsCreateOrConnectWithoutMatchInput = {
  where: Prisma.MatchPlayerStatsWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutMatchInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput>
}

export type MatchPlayerStatsCreateManyMatchInputEnvelope = {
  data: Prisma.MatchPlayerStatsCreateManyMatchInput | Prisma.MatchPlayerStatsCreateManyMatchInput[]
  skipDuplicates?: boolean
}

export type MatchPlayerStatsUpsertWithWhereUniqueWithoutMatchInput = {
  where: Prisma.MatchPlayerStatsWhereUniqueInput
  update: Prisma.XOR<Prisma.MatchPlayerStatsUpdateWithoutMatchInput, Prisma.MatchPlayerStatsUncheckedUpdateWithoutMatchInput>
  create: Prisma.XOR<Prisma.MatchPlayerStatsCreateWithoutMatchInput, Prisma.MatchPlayerStatsUncheckedCreateWithoutMatchInput>
}

export type MatchPlayerStatsUpdateWithWhereUniqueWithoutMatchInput = {
  where: Prisma.MatchPlayerStatsWhereUniqueInput
  data: Prisma.XOR<Prisma.MatchPlayerStatsUpdateWithoutMatchInput, Prisma.MatchPlayerStatsUncheckedUpdateWithoutMatchInput>
}

export type MatchPlayerStatsUpdateManyWithWhereWithoutMatchInput = {
  where: Prisma.MatchPlayerStatsScalarWhereInput
  data: Prisma.XOR<Prisma.MatchPlayerStatsUpdateManyMutationInput, Prisma.MatchPlayerStatsUncheckedUpdateManyWithoutMatchInput>
}

export type MatchPlayerStatsCreateManyPlayerInput = {
  id?: string
  goals?: number
  assists?: number
  yellowCards?: number
  redCards?: number
  matchId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MatchPlayerStatsUpdateWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  match?: Prisma.MatchUpdateOneRequiredWithoutPlayerStatsNestedInput
}

export type MatchPlayerStatsUncheckedUpdateWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  matchId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MatchPlayerStatsUncheckedUpdateManyWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  matchId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MatchPlayerStatsCreateManyMatchInput = {
  id?: string
  goals?: number
  assists?: number
  yellowCards?: number
  redCards?: number
  playerId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MatchPlayerStatsUpdateWithoutMatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  player?: Prisma.PlayerUpdateOneRequiredWithoutStatsNestedInput
}

export type MatchPlayerStatsUncheckedUpdateWithoutMatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MatchPlayerStatsUncheckedUpdateManyWithoutMatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  goals?: Prisma.IntFieldUpdateOperationsInput | number
  assists?: Prisma.IntFieldUpdateOperationsInput | number
  yellowCards?: Prisma.IntFieldUpdateOperationsInput | number
  redCards?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MatchPlayerStatsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  goals?: boolean
  assists?: boolean
  yellowCards?: boolean
  redCards?: boolean
  matchId?: boolean
  playerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  match?: boolean | Prisma.MatchDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["matchPlayerStats"]>

export type MatchPlayerStatsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  goals?: boolean
  assists?: boolean
  yellowCards?: boolean
  redCards?: boolean
  matchId?: boolean
  playerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  match?: boolean | Prisma.MatchDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["matchPlayerStats"]>

export type MatchPlayerStatsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  goals?: boolean
  assists?: boolean
  yellowCards?: boolean
  redCards?: boolean
  matchId?: boolean
  playerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  match?: boolean | Prisma.MatchDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["matchPlayerStats"]>

export type MatchPlayerStatsSelectScalar = {
  id?: boolean
  goals?: boolean
  assists?: boolean
  yellowCards?: boolean
  redCards?: boolean
  matchId?: boolean
  playerId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MatchPlayerStatsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "goals" | "assists" | "yellowCards" | "redCards" | "matchId" | "playerId" | "createdAt" | "updatedAt", ExtArgs["result"]["matchPlayerStats"]>
export type MatchPlayerStatsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  match?: boolean | Prisma.MatchDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}
export type MatchPlayerStatsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  match?: boolean | Prisma.MatchDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}
export type MatchPlayerStatsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  match?: boolean | Prisma.MatchDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}

export type $MatchPlayerStatsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MatchPlayerStats"
  objects: {
    match: Prisma.$MatchPayload<ExtArgs>
    player: Prisma.$PlayerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    goals: number
    assists: number
    yellowCards: number
    redCards: number
    matchId: string
    playerId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["matchPlayerStats"]>
  composites: {}
}

export type MatchPlayerStatsGetPayload<S extends boolean | null | undefined | MatchPlayerStatsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload, S>

export type MatchPlayerStatsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MatchPlayerStatsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MatchPlayerStatsCountAggregateInputType | true
  }

export interface MatchPlayerStatsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MatchPlayerStats'], meta: { name: 'MatchPlayerStats' } }
  /**
   * Find zero or one MatchPlayerStats that matches the filter.
   * @param {MatchPlayerStatsFindUniqueArgs} args - Arguments to find a MatchPlayerStats
   * @example
   * // Get one MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MatchPlayerStatsFindUniqueArgs>(args: Prisma.SelectSubset<T, MatchPlayerStatsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MatchPlayerStatsClient<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MatchPlayerStats that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MatchPlayerStatsFindUniqueOrThrowArgs} args - Arguments to find a MatchPlayerStats
   * @example
   * // Get one MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MatchPlayerStatsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MatchPlayerStatsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MatchPlayerStatsClient<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MatchPlayerStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchPlayerStatsFindFirstArgs} args - Arguments to find a MatchPlayerStats
   * @example
   * // Get one MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MatchPlayerStatsFindFirstArgs>(args?: Prisma.SelectSubset<T, MatchPlayerStatsFindFirstArgs<ExtArgs>>): Prisma.Prisma__MatchPlayerStatsClient<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MatchPlayerStats that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchPlayerStatsFindFirstOrThrowArgs} args - Arguments to find a MatchPlayerStats
   * @example
   * // Get one MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MatchPlayerStatsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MatchPlayerStatsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MatchPlayerStatsClient<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MatchPlayerStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchPlayerStatsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.findMany()
   * 
   * // Get first 10 MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const matchPlayerStatsWithIdOnly = await prisma.matchPlayerStats.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MatchPlayerStatsFindManyArgs>(args?: Prisma.SelectSubset<T, MatchPlayerStatsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MatchPlayerStats.
   * @param {MatchPlayerStatsCreateArgs} args - Arguments to create a MatchPlayerStats.
   * @example
   * // Create one MatchPlayerStats
   * const MatchPlayerStats = await prisma.matchPlayerStats.create({
   *   data: {
   *     // ... data to create a MatchPlayerStats
   *   }
   * })
   * 
   */
  create<T extends MatchPlayerStatsCreateArgs>(args: Prisma.SelectSubset<T, MatchPlayerStatsCreateArgs<ExtArgs>>): Prisma.Prisma__MatchPlayerStatsClient<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MatchPlayerStats.
   * @param {MatchPlayerStatsCreateManyArgs} args - Arguments to create many MatchPlayerStats.
   * @example
   * // Create many MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MatchPlayerStatsCreateManyArgs>(args?: Prisma.SelectSubset<T, MatchPlayerStatsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MatchPlayerStats and returns the data saved in the database.
   * @param {MatchPlayerStatsCreateManyAndReturnArgs} args - Arguments to create many MatchPlayerStats.
   * @example
   * // Create many MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MatchPlayerStats and only return the `id`
   * const matchPlayerStatsWithIdOnly = await prisma.matchPlayerStats.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MatchPlayerStatsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MatchPlayerStatsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MatchPlayerStats.
   * @param {MatchPlayerStatsDeleteArgs} args - Arguments to delete one MatchPlayerStats.
   * @example
   * // Delete one MatchPlayerStats
   * const MatchPlayerStats = await prisma.matchPlayerStats.delete({
   *   where: {
   *     // ... filter to delete one MatchPlayerStats
   *   }
   * })
   * 
   */
  delete<T extends MatchPlayerStatsDeleteArgs>(args: Prisma.SelectSubset<T, MatchPlayerStatsDeleteArgs<ExtArgs>>): Prisma.Prisma__MatchPlayerStatsClient<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MatchPlayerStats.
   * @param {MatchPlayerStatsUpdateArgs} args - Arguments to update one MatchPlayerStats.
   * @example
   * // Update one MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MatchPlayerStatsUpdateArgs>(args: Prisma.SelectSubset<T, MatchPlayerStatsUpdateArgs<ExtArgs>>): Prisma.Prisma__MatchPlayerStatsClient<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MatchPlayerStats.
   * @param {MatchPlayerStatsDeleteManyArgs} args - Arguments to filter MatchPlayerStats to delete.
   * @example
   * // Delete a few MatchPlayerStats
   * const { count } = await prisma.matchPlayerStats.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MatchPlayerStatsDeleteManyArgs>(args?: Prisma.SelectSubset<T, MatchPlayerStatsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MatchPlayerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchPlayerStatsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MatchPlayerStatsUpdateManyArgs>(args: Prisma.SelectSubset<T, MatchPlayerStatsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MatchPlayerStats and returns the data updated in the database.
   * @param {MatchPlayerStatsUpdateManyAndReturnArgs} args - Arguments to update many MatchPlayerStats.
   * @example
   * // Update many MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MatchPlayerStats and only return the `id`
   * const matchPlayerStatsWithIdOnly = await prisma.matchPlayerStats.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MatchPlayerStatsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MatchPlayerStatsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MatchPlayerStats.
   * @param {MatchPlayerStatsUpsertArgs} args - Arguments to update or create a MatchPlayerStats.
   * @example
   * // Update or create a MatchPlayerStats
   * const matchPlayerStats = await prisma.matchPlayerStats.upsert({
   *   create: {
   *     // ... data to create a MatchPlayerStats
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MatchPlayerStats we want to update
   *   }
   * })
   */
  upsert<T extends MatchPlayerStatsUpsertArgs>(args: Prisma.SelectSubset<T, MatchPlayerStatsUpsertArgs<ExtArgs>>): Prisma.Prisma__MatchPlayerStatsClient<runtime.Types.Result.GetResult<Prisma.$MatchPlayerStatsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MatchPlayerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchPlayerStatsCountArgs} args - Arguments to filter MatchPlayerStats to count.
   * @example
   * // Count the number of MatchPlayerStats
   * const count = await prisma.matchPlayerStats.count({
   *   where: {
   *     // ... the filter for the MatchPlayerStats we want to count
   *   }
   * })
  **/
  count<T extends MatchPlayerStatsCountArgs>(
    args?: Prisma.Subset<T, MatchPlayerStatsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MatchPlayerStatsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MatchPlayerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchPlayerStatsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MatchPlayerStatsAggregateArgs>(args: Prisma.Subset<T, MatchPlayerStatsAggregateArgs>): Prisma.PrismaPromise<GetMatchPlayerStatsAggregateType<T>>

  /**
   * Group by MatchPlayerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchPlayerStatsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MatchPlayerStatsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MatchPlayerStatsGroupByArgs['orderBy'] }
      : { orderBy?: MatchPlayerStatsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MatchPlayerStatsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMatchPlayerStatsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MatchPlayerStats model
 */
readonly fields: MatchPlayerStatsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MatchPlayerStats.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MatchPlayerStatsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  match<T extends Prisma.MatchDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MatchDefaultArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  player<T extends Prisma.PlayerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlayerDefaultArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MatchPlayerStats model
 */
export interface MatchPlayerStatsFieldRefs {
  readonly id: Prisma.FieldRef<"MatchPlayerStats", 'String'>
  readonly goals: Prisma.FieldRef<"MatchPlayerStats", 'Int'>
  readonly assists: Prisma.FieldRef<"MatchPlayerStats", 'Int'>
  readonly yellowCards: Prisma.FieldRef<"MatchPlayerStats", 'Int'>
  readonly redCards: Prisma.FieldRef<"MatchPlayerStats", 'Int'>
  readonly matchId: Prisma.FieldRef<"MatchPlayerStats", 'String'>
  readonly playerId: Prisma.FieldRef<"MatchPlayerStats", 'String'>
  readonly createdAt: Prisma.FieldRef<"MatchPlayerStats", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MatchPlayerStats", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MatchPlayerStats findUnique
 */
export type MatchPlayerStatsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
  /**
   * Filter, which MatchPlayerStats to fetch.
   */
  where: Prisma.MatchPlayerStatsWhereUniqueInput
}

/**
 * MatchPlayerStats findUniqueOrThrow
 */
export type MatchPlayerStatsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
  /**
   * Filter, which MatchPlayerStats to fetch.
   */
  where: Prisma.MatchPlayerStatsWhereUniqueInput
}

/**
 * MatchPlayerStats findFirst
 */
export type MatchPlayerStatsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
  /**
   * Filter, which MatchPlayerStats to fetch.
   */
  where?: Prisma.MatchPlayerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MatchPlayerStats to fetch.
   */
  orderBy?: Prisma.MatchPlayerStatsOrderByWithRelationInput | Prisma.MatchPlayerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MatchPlayerStats.
   */
  cursor?: Prisma.MatchPlayerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MatchPlayerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MatchPlayerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MatchPlayerStats.
   */
  distinct?: Prisma.MatchPlayerStatsScalarFieldEnum | Prisma.MatchPlayerStatsScalarFieldEnum[]
}

/**
 * MatchPlayerStats findFirstOrThrow
 */
export type MatchPlayerStatsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
  /**
   * Filter, which MatchPlayerStats to fetch.
   */
  where?: Prisma.MatchPlayerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MatchPlayerStats to fetch.
   */
  orderBy?: Prisma.MatchPlayerStatsOrderByWithRelationInput | Prisma.MatchPlayerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MatchPlayerStats.
   */
  cursor?: Prisma.MatchPlayerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MatchPlayerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MatchPlayerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MatchPlayerStats.
   */
  distinct?: Prisma.MatchPlayerStatsScalarFieldEnum | Prisma.MatchPlayerStatsScalarFieldEnum[]
}

/**
 * MatchPlayerStats findMany
 */
export type MatchPlayerStatsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
  /**
   * Filter, which MatchPlayerStats to fetch.
   */
  where?: Prisma.MatchPlayerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MatchPlayerStats to fetch.
   */
  orderBy?: Prisma.MatchPlayerStatsOrderByWithRelationInput | Prisma.MatchPlayerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MatchPlayerStats.
   */
  cursor?: Prisma.MatchPlayerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MatchPlayerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MatchPlayerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MatchPlayerStats.
   */
  distinct?: Prisma.MatchPlayerStatsScalarFieldEnum | Prisma.MatchPlayerStatsScalarFieldEnum[]
}

/**
 * MatchPlayerStats create
 */
export type MatchPlayerStatsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
  /**
   * The data needed to create a MatchPlayerStats.
   */
  data: Prisma.XOR<Prisma.MatchPlayerStatsCreateInput, Prisma.MatchPlayerStatsUncheckedCreateInput>
}

/**
 * MatchPlayerStats createMany
 */
export type MatchPlayerStatsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MatchPlayerStats.
   */
  data: Prisma.MatchPlayerStatsCreateManyInput | Prisma.MatchPlayerStatsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MatchPlayerStats createManyAndReturn
 */
export type MatchPlayerStatsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * The data used to create many MatchPlayerStats.
   */
  data: Prisma.MatchPlayerStatsCreateManyInput | Prisma.MatchPlayerStatsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MatchPlayerStats update
 */
export type MatchPlayerStatsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
  /**
   * The data needed to update a MatchPlayerStats.
   */
  data: Prisma.XOR<Prisma.MatchPlayerStatsUpdateInput, Prisma.MatchPlayerStatsUncheckedUpdateInput>
  /**
   * Choose, which MatchPlayerStats to update.
   */
  where: Prisma.MatchPlayerStatsWhereUniqueInput
}

/**
 * MatchPlayerStats updateMany
 */
export type MatchPlayerStatsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MatchPlayerStats.
   */
  data: Prisma.XOR<Prisma.MatchPlayerStatsUpdateManyMutationInput, Prisma.MatchPlayerStatsUncheckedUpdateManyInput>
  /**
   * Filter which MatchPlayerStats to update
   */
  where?: Prisma.MatchPlayerStatsWhereInput
  /**
   * Limit how many MatchPlayerStats to update.
   */
  limit?: number
}

/**
 * MatchPlayerStats updateManyAndReturn
 */
export type MatchPlayerStatsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * The data used to update MatchPlayerStats.
   */
  data: Prisma.XOR<Prisma.MatchPlayerStatsUpdateManyMutationInput, Prisma.MatchPlayerStatsUncheckedUpdateManyInput>
  /**
   * Filter which MatchPlayerStats to update
   */
  where?: Prisma.MatchPlayerStatsWhereInput
  /**
   * Limit how many MatchPlayerStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MatchPlayerStats upsert
 */
export type MatchPlayerStatsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
  /**
   * The filter to search for the MatchPlayerStats to update in case it exists.
   */
  where: Prisma.MatchPlayerStatsWhereUniqueInput
  /**
   * In case the MatchPlayerStats found by the `where` argument doesn't exist, create a new MatchPlayerStats with this data.
   */
  create: Prisma.XOR<Prisma.MatchPlayerStatsCreateInput, Prisma.MatchPlayerStatsUncheckedCreateInput>
  /**
   * In case the MatchPlayerStats was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MatchPlayerStatsUpdateInput, Prisma.MatchPlayerStatsUncheckedUpdateInput>
}

/**
 * MatchPlayerStats delete
 */
export type MatchPlayerStatsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
  /**
   * Filter which MatchPlayerStats to delete.
   */
  where: Prisma.MatchPlayerStatsWhereUniqueInput
}

/**
 * MatchPlayerStats deleteMany
 */
export type MatchPlayerStatsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MatchPlayerStats to delete
   */
  where?: Prisma.MatchPlayerStatsWhereInput
  /**
   * Limit how many MatchPlayerStats to delete.
   */
  limit?: number
}

/**
 * MatchPlayerStats without action
 */
export type MatchPlayerStatsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchPlayerStats
   */
  select?: Prisma.MatchPlayerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MatchPlayerStats
   */
  omit?: Prisma.MatchPlayerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchPlayerStatsInclude<ExtArgs> | null
}
