
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PendingRefund` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PendingRefund
 * 
 */
export type PendingRefundModel = runtime.Types.Result.DefaultSelection<Prisma.$PendingRefundPayload>

export type AggregatePendingRefund = {
  _count: PendingRefundCountAggregateOutputType | null
  _avg: PendingRefundAvgAggregateOutputType | null
  _sum: PendingRefundSumAggregateOutputType | null
  _min: PendingRefundMinAggregateOutputType | null
  _max: PendingRefundMaxAggregateOutputType | null
}

export type PendingRefundAvgAggregateOutputType = {
  amount: number | null
  attempts: number | null
}

export type PendingRefundSumAggregateOutputType = {
  amount: number | null
  attempts: number | null
}

export type PendingRefundMinAggregateOutputType = {
  id: string | null
  userId: string | null
  twitchUsername: string | null
  amount: number | null
  reason: string | null
  wizebotDebitTxId: string | null
  status: $Enums.RefundStatus | null
  attempts: number | null
  lastError: string | null
  refundTxId: string | null
  refundedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PendingRefundMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  twitchUsername: string | null
  amount: number | null
  reason: string | null
  wizebotDebitTxId: string | null
  status: $Enums.RefundStatus | null
  attempts: number | null
  lastError: string | null
  refundTxId: string | null
  refundedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PendingRefundCountAggregateOutputType = {
  id: number
  userId: number
  twitchUsername: number
  amount: number
  reason: number
  wizebotDebitTxId: number
  status: number
  attempts: number
  lastError: number
  refundTxId: number
  refundedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PendingRefundAvgAggregateInputType = {
  amount?: true
  attempts?: true
}

export type PendingRefundSumAggregateInputType = {
  amount?: true
  attempts?: true
}

export type PendingRefundMinAggregateInputType = {
  id?: true
  userId?: true
  twitchUsername?: true
  amount?: true
  reason?: true
  wizebotDebitTxId?: true
  status?: true
  attempts?: true
  lastError?: true
  refundTxId?: true
  refundedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type PendingRefundMaxAggregateInputType = {
  id?: true
  userId?: true
  twitchUsername?: true
  amount?: true
  reason?: true
  wizebotDebitTxId?: true
  status?: true
  attempts?: true
  lastError?: true
  refundTxId?: true
  refundedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type PendingRefundCountAggregateInputType = {
  id?: true
  userId?: true
  twitchUsername?: true
  amount?: true
  reason?: true
  wizebotDebitTxId?: true
  status?: true
  attempts?: true
  lastError?: true
  refundTxId?: true
  refundedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PendingRefundAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PendingRefund to aggregate.
   */
  where?: Prisma.PendingRefundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PendingRefunds to fetch.
   */
  orderBy?: Prisma.PendingRefundOrderByWithRelationInput | Prisma.PendingRefundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PendingRefundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PendingRefunds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PendingRefunds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PendingRefunds
  **/
  _count?: true | PendingRefundCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PendingRefundAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PendingRefundSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PendingRefundMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PendingRefundMaxAggregateInputType
}

export type GetPendingRefundAggregateType<T extends PendingRefundAggregateArgs> = {
      [P in keyof T & keyof AggregatePendingRefund]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePendingRefund[P]>
    : Prisma.GetScalarType<T[P], AggregatePendingRefund[P]>
}




export type PendingRefundGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PendingRefundWhereInput
  orderBy?: Prisma.PendingRefundOrderByWithAggregationInput | Prisma.PendingRefundOrderByWithAggregationInput[]
  by: Prisma.PendingRefundScalarFieldEnum[] | Prisma.PendingRefundScalarFieldEnum
  having?: Prisma.PendingRefundScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PendingRefundCountAggregateInputType | true
  _avg?: PendingRefundAvgAggregateInputType
  _sum?: PendingRefundSumAggregateInputType
  _min?: PendingRefundMinAggregateInputType
  _max?: PendingRefundMaxAggregateInputType
}

export type PendingRefundGroupByOutputType = {
  id: string
  userId: string
  twitchUsername: string
  amount: number
  reason: string
  wizebotDebitTxId: string | null
  status: $Enums.RefundStatus
  attempts: number
  lastError: string | null
  refundTxId: string | null
  refundedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: PendingRefundCountAggregateOutputType | null
  _avg: PendingRefundAvgAggregateOutputType | null
  _sum: PendingRefundSumAggregateOutputType | null
  _min: PendingRefundMinAggregateOutputType | null
  _max: PendingRefundMaxAggregateOutputType | null
}

export type GetPendingRefundGroupByPayload<T extends PendingRefundGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PendingRefundGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PendingRefundGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PendingRefundGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PendingRefundGroupByOutputType[P]>
      }
    >
  >



export type PendingRefundWhereInput = {
  AND?: Prisma.PendingRefundWhereInput | Prisma.PendingRefundWhereInput[]
  OR?: Prisma.PendingRefundWhereInput[]
  NOT?: Prisma.PendingRefundWhereInput | Prisma.PendingRefundWhereInput[]
  id?: Prisma.UuidFilter<"PendingRefund"> | string
  userId?: Prisma.UuidFilter<"PendingRefund"> | string
  twitchUsername?: Prisma.StringFilter<"PendingRefund"> | string
  amount?: Prisma.IntFilter<"PendingRefund"> | number
  reason?: Prisma.StringFilter<"PendingRefund"> | string
  wizebotDebitTxId?: Prisma.StringNullableFilter<"PendingRefund"> | string | null
  status?: Prisma.EnumRefundStatusFilter<"PendingRefund"> | $Enums.RefundStatus
  attempts?: Prisma.IntFilter<"PendingRefund"> | number
  lastError?: Prisma.StringNullableFilter<"PendingRefund"> | string | null
  refundTxId?: Prisma.StringNullableFilter<"PendingRefund"> | string | null
  refundedAt?: Prisma.DateTimeNullableFilter<"PendingRefund"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"PendingRefund"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PendingRefund"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PendingRefundOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  twitchUsername?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  lastError?: Prisma.SortOrderInput | Prisma.SortOrder
  refundTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  refundedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type PendingRefundWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PendingRefundWhereInput | Prisma.PendingRefundWhereInput[]
  OR?: Prisma.PendingRefundWhereInput[]
  NOT?: Prisma.PendingRefundWhereInput | Prisma.PendingRefundWhereInput[]
  userId?: Prisma.UuidFilter<"PendingRefund"> | string
  twitchUsername?: Prisma.StringFilter<"PendingRefund"> | string
  amount?: Prisma.IntFilter<"PendingRefund"> | number
  reason?: Prisma.StringFilter<"PendingRefund"> | string
  wizebotDebitTxId?: Prisma.StringNullableFilter<"PendingRefund"> | string | null
  status?: Prisma.EnumRefundStatusFilter<"PendingRefund"> | $Enums.RefundStatus
  attempts?: Prisma.IntFilter<"PendingRefund"> | number
  lastError?: Prisma.StringNullableFilter<"PendingRefund"> | string | null
  refundTxId?: Prisma.StringNullableFilter<"PendingRefund"> | string | null
  refundedAt?: Prisma.DateTimeNullableFilter<"PendingRefund"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"PendingRefund"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PendingRefund"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type PendingRefundOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  twitchUsername?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  lastError?: Prisma.SortOrderInput | Prisma.SortOrder
  refundTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  refundedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PendingRefundCountOrderByAggregateInput
  _avg?: Prisma.PendingRefundAvgOrderByAggregateInput
  _max?: Prisma.PendingRefundMaxOrderByAggregateInput
  _min?: Prisma.PendingRefundMinOrderByAggregateInput
  _sum?: Prisma.PendingRefundSumOrderByAggregateInput
}

export type PendingRefundScalarWhereWithAggregatesInput = {
  AND?: Prisma.PendingRefundScalarWhereWithAggregatesInput | Prisma.PendingRefundScalarWhereWithAggregatesInput[]
  OR?: Prisma.PendingRefundScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PendingRefundScalarWhereWithAggregatesInput | Prisma.PendingRefundScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"PendingRefund"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"PendingRefund"> | string
  twitchUsername?: Prisma.StringWithAggregatesFilter<"PendingRefund"> | string
  amount?: Prisma.IntWithAggregatesFilter<"PendingRefund"> | number
  reason?: Prisma.StringWithAggregatesFilter<"PendingRefund"> | string
  wizebotDebitTxId?: Prisma.StringNullableWithAggregatesFilter<"PendingRefund"> | string | null
  status?: Prisma.EnumRefundStatusWithAggregatesFilter<"PendingRefund"> | $Enums.RefundStatus
  attempts?: Prisma.IntWithAggregatesFilter<"PendingRefund"> | number
  lastError?: Prisma.StringNullableWithAggregatesFilter<"PendingRefund"> | string | null
  refundTxId?: Prisma.StringNullableWithAggregatesFilter<"PendingRefund"> | string | null
  refundedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PendingRefund"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PendingRefund"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PendingRefund"> | Date | string
}

export type PendingRefundCreateInput = {
  id?: string
  twitchUsername: string
  amount: number
  reason: string
  wizebotDebitTxId?: string | null
  status?: $Enums.RefundStatus
  attempts?: number
  lastError?: string | null
  refundTxId?: string | null
  refundedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPendingRefundsInput
}

export type PendingRefundUncheckedCreateInput = {
  id?: string
  userId: string
  twitchUsername: string
  amount: number
  reason: string
  wizebotDebitTxId?: string | null
  status?: $Enums.RefundStatus
  attempts?: number
  lastError?: string | null
  refundTxId?: string | null
  refundedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PendingRefundUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  twitchUsername?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumRefundStatusFieldUpdateOperationsInput | $Enums.RefundStatus
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPendingRefundsNestedInput
}

export type PendingRefundUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  twitchUsername?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumRefundStatusFieldUpdateOperationsInput | $Enums.RefundStatus
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PendingRefundCreateManyInput = {
  id?: string
  userId: string
  twitchUsername: string
  amount: number
  reason: string
  wizebotDebitTxId?: string | null
  status?: $Enums.RefundStatus
  attempts?: number
  lastError?: string | null
  refundTxId?: string | null
  refundedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PendingRefundUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  twitchUsername?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumRefundStatusFieldUpdateOperationsInput | $Enums.RefundStatus
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PendingRefundUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  twitchUsername?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumRefundStatusFieldUpdateOperationsInput | $Enums.RefundStatus
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PendingRefundListRelationFilter = {
  every?: Prisma.PendingRefundWhereInput
  some?: Prisma.PendingRefundWhereInput
  none?: Prisma.PendingRefundWhereInput
}

export type PendingRefundOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PendingRefundCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  twitchUsername?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  refundTxId?: Prisma.SortOrder
  refundedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PendingRefundAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
}

export type PendingRefundMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  twitchUsername?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  refundTxId?: Prisma.SortOrder
  refundedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PendingRefundMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  twitchUsername?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  wizebotDebitTxId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  refundTxId?: Prisma.SortOrder
  refundedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PendingRefundSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
}

export type PendingRefundCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PendingRefundCreateWithoutUserInput, Prisma.PendingRefundUncheckedCreateWithoutUserInput> | Prisma.PendingRefundCreateWithoutUserInput[] | Prisma.PendingRefundUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PendingRefundCreateOrConnectWithoutUserInput | Prisma.PendingRefundCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PendingRefundCreateManyUserInputEnvelope
  connect?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
}

export type PendingRefundUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PendingRefundCreateWithoutUserInput, Prisma.PendingRefundUncheckedCreateWithoutUserInput> | Prisma.PendingRefundCreateWithoutUserInput[] | Prisma.PendingRefundUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PendingRefundCreateOrConnectWithoutUserInput | Prisma.PendingRefundCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PendingRefundCreateManyUserInputEnvelope
  connect?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
}

export type PendingRefundUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PendingRefundCreateWithoutUserInput, Prisma.PendingRefundUncheckedCreateWithoutUserInput> | Prisma.PendingRefundCreateWithoutUserInput[] | Prisma.PendingRefundUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PendingRefundCreateOrConnectWithoutUserInput | Prisma.PendingRefundCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PendingRefundUpsertWithWhereUniqueWithoutUserInput | Prisma.PendingRefundUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PendingRefundCreateManyUserInputEnvelope
  set?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
  disconnect?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
  delete?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
  connect?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
  update?: Prisma.PendingRefundUpdateWithWhereUniqueWithoutUserInput | Prisma.PendingRefundUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PendingRefundUpdateManyWithWhereWithoutUserInput | Prisma.PendingRefundUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PendingRefundScalarWhereInput | Prisma.PendingRefundScalarWhereInput[]
}

export type PendingRefundUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PendingRefundCreateWithoutUserInput, Prisma.PendingRefundUncheckedCreateWithoutUserInput> | Prisma.PendingRefundCreateWithoutUserInput[] | Prisma.PendingRefundUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PendingRefundCreateOrConnectWithoutUserInput | Prisma.PendingRefundCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PendingRefundUpsertWithWhereUniqueWithoutUserInput | Prisma.PendingRefundUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PendingRefundCreateManyUserInputEnvelope
  set?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
  disconnect?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
  delete?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
  connect?: Prisma.PendingRefundWhereUniqueInput | Prisma.PendingRefundWhereUniqueInput[]
  update?: Prisma.PendingRefundUpdateWithWhereUniqueWithoutUserInput | Prisma.PendingRefundUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PendingRefundUpdateManyWithWhereWithoutUserInput | Prisma.PendingRefundUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PendingRefundScalarWhereInput | Prisma.PendingRefundScalarWhereInput[]
}

export type EnumRefundStatusFieldUpdateOperationsInput = {
  set?: $Enums.RefundStatus
}

export type PendingRefundCreateWithoutUserInput = {
  id?: string
  twitchUsername: string
  amount: number
  reason: string
  wizebotDebitTxId?: string | null
  status?: $Enums.RefundStatus
  attempts?: number
  lastError?: string | null
  refundTxId?: string | null
  refundedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PendingRefundUncheckedCreateWithoutUserInput = {
  id?: string
  twitchUsername: string
  amount: number
  reason: string
  wizebotDebitTxId?: string | null
  status?: $Enums.RefundStatus
  attempts?: number
  lastError?: string | null
  refundTxId?: string | null
  refundedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PendingRefundCreateOrConnectWithoutUserInput = {
  where: Prisma.PendingRefundWhereUniqueInput
  create: Prisma.XOR<Prisma.PendingRefundCreateWithoutUserInput, Prisma.PendingRefundUncheckedCreateWithoutUserInput>
}

export type PendingRefundCreateManyUserInputEnvelope = {
  data: Prisma.PendingRefundCreateManyUserInput | Prisma.PendingRefundCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PendingRefundUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PendingRefundWhereUniqueInput
  update: Prisma.XOR<Prisma.PendingRefundUpdateWithoutUserInput, Prisma.PendingRefundUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PendingRefundCreateWithoutUserInput, Prisma.PendingRefundUncheckedCreateWithoutUserInput>
}

export type PendingRefundUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PendingRefundWhereUniqueInput
  data: Prisma.XOR<Prisma.PendingRefundUpdateWithoutUserInput, Prisma.PendingRefundUncheckedUpdateWithoutUserInput>
}

export type PendingRefundUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PendingRefundScalarWhereInput
  data: Prisma.XOR<Prisma.PendingRefundUpdateManyMutationInput, Prisma.PendingRefundUncheckedUpdateManyWithoutUserInput>
}

export type PendingRefundScalarWhereInput = {
  AND?: Prisma.PendingRefundScalarWhereInput | Prisma.PendingRefundScalarWhereInput[]
  OR?: Prisma.PendingRefundScalarWhereInput[]
  NOT?: Prisma.PendingRefundScalarWhereInput | Prisma.PendingRefundScalarWhereInput[]
  id?: Prisma.UuidFilter<"PendingRefund"> | string
  userId?: Prisma.UuidFilter<"PendingRefund"> | string
  twitchUsername?: Prisma.StringFilter<"PendingRefund"> | string
  amount?: Prisma.IntFilter<"PendingRefund"> | number
  reason?: Prisma.StringFilter<"PendingRefund"> | string
  wizebotDebitTxId?: Prisma.StringNullableFilter<"PendingRefund"> | string | null
  status?: Prisma.EnumRefundStatusFilter<"PendingRefund"> | $Enums.RefundStatus
  attempts?: Prisma.IntFilter<"PendingRefund"> | number
  lastError?: Prisma.StringNullableFilter<"PendingRefund"> | string | null
  refundTxId?: Prisma.StringNullableFilter<"PendingRefund"> | string | null
  refundedAt?: Prisma.DateTimeNullableFilter<"PendingRefund"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"PendingRefund"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PendingRefund"> | Date | string
}

export type PendingRefundCreateManyUserInput = {
  id?: string
  twitchUsername: string
  amount: number
  reason: string
  wizebotDebitTxId?: string | null
  status?: $Enums.RefundStatus
  attempts?: number
  lastError?: string | null
  refundTxId?: string | null
  refundedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PendingRefundUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  twitchUsername?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumRefundStatusFieldUpdateOperationsInput | $Enums.RefundStatus
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PendingRefundUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  twitchUsername?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumRefundStatusFieldUpdateOperationsInput | $Enums.RefundStatus
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PendingRefundUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  twitchUsername?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  wizebotDebitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumRefundStatusFieldUpdateOperationsInput | $Enums.RefundStatus
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refundedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PendingRefundSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  twitchUsername?: boolean
  amount?: boolean
  reason?: boolean
  wizebotDebitTxId?: boolean
  status?: boolean
  attempts?: boolean
  lastError?: boolean
  refundTxId?: boolean
  refundedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pendingRefund"]>

export type PendingRefundSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  twitchUsername?: boolean
  amount?: boolean
  reason?: boolean
  wizebotDebitTxId?: boolean
  status?: boolean
  attempts?: boolean
  lastError?: boolean
  refundTxId?: boolean
  refundedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pendingRefund"]>

export type PendingRefundSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  twitchUsername?: boolean
  amount?: boolean
  reason?: boolean
  wizebotDebitTxId?: boolean
  status?: boolean
  attempts?: boolean
  lastError?: boolean
  refundTxId?: boolean
  refundedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pendingRefund"]>

export type PendingRefundSelectScalar = {
  id?: boolean
  userId?: boolean
  twitchUsername?: boolean
  amount?: boolean
  reason?: boolean
  wizebotDebitTxId?: boolean
  status?: boolean
  attempts?: boolean
  lastError?: boolean
  refundTxId?: boolean
  refundedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PendingRefundOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "twitchUsername" | "amount" | "reason" | "wizebotDebitTxId" | "status" | "attempts" | "lastError" | "refundTxId" | "refundedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["pendingRefund"]>
export type PendingRefundInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PendingRefundIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PendingRefundIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PendingRefundPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PendingRefund"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    twitchUsername: string
    amount: number
    reason: string
    wizebotDebitTxId: string | null
    status: $Enums.RefundStatus
    attempts: number
    lastError: string | null
    refundTxId: string | null
    refundedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pendingRefund"]>
  composites: {}
}

export type PendingRefundGetPayload<S extends boolean | null | undefined | PendingRefundDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload, S>

export type PendingRefundCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PendingRefundFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PendingRefundCountAggregateInputType | true
  }

export interface PendingRefundDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PendingRefund'], meta: { name: 'PendingRefund' } }
  /**
   * Find zero or one PendingRefund that matches the filter.
   * @param {PendingRefundFindUniqueArgs} args - Arguments to find a PendingRefund
   * @example
   * // Get one PendingRefund
   * const pendingRefund = await prisma.pendingRefund.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PendingRefundFindUniqueArgs>(args: Prisma.SelectSubset<T, PendingRefundFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PendingRefundClient<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PendingRefund that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PendingRefundFindUniqueOrThrowArgs} args - Arguments to find a PendingRefund
   * @example
   * // Get one PendingRefund
   * const pendingRefund = await prisma.pendingRefund.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PendingRefundFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PendingRefundFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PendingRefundClient<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PendingRefund that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PendingRefundFindFirstArgs} args - Arguments to find a PendingRefund
   * @example
   * // Get one PendingRefund
   * const pendingRefund = await prisma.pendingRefund.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PendingRefundFindFirstArgs>(args?: Prisma.SelectSubset<T, PendingRefundFindFirstArgs<ExtArgs>>): Prisma.Prisma__PendingRefundClient<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PendingRefund that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PendingRefundFindFirstOrThrowArgs} args - Arguments to find a PendingRefund
   * @example
   * // Get one PendingRefund
   * const pendingRefund = await prisma.pendingRefund.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PendingRefundFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PendingRefundFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PendingRefundClient<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PendingRefunds that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PendingRefundFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PendingRefunds
   * const pendingRefunds = await prisma.pendingRefund.findMany()
   * 
   * // Get first 10 PendingRefunds
   * const pendingRefunds = await prisma.pendingRefund.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pendingRefundWithIdOnly = await prisma.pendingRefund.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PendingRefundFindManyArgs>(args?: Prisma.SelectSubset<T, PendingRefundFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PendingRefund.
   * @param {PendingRefundCreateArgs} args - Arguments to create a PendingRefund.
   * @example
   * // Create one PendingRefund
   * const PendingRefund = await prisma.pendingRefund.create({
   *   data: {
   *     // ... data to create a PendingRefund
   *   }
   * })
   * 
   */
  create<T extends PendingRefundCreateArgs>(args: Prisma.SelectSubset<T, PendingRefundCreateArgs<ExtArgs>>): Prisma.Prisma__PendingRefundClient<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PendingRefunds.
   * @param {PendingRefundCreateManyArgs} args - Arguments to create many PendingRefunds.
   * @example
   * // Create many PendingRefunds
   * const pendingRefund = await prisma.pendingRefund.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PendingRefundCreateManyArgs>(args?: Prisma.SelectSubset<T, PendingRefundCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PendingRefunds and returns the data saved in the database.
   * @param {PendingRefundCreateManyAndReturnArgs} args - Arguments to create many PendingRefunds.
   * @example
   * // Create many PendingRefunds
   * const pendingRefund = await prisma.pendingRefund.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PendingRefunds and only return the `id`
   * const pendingRefundWithIdOnly = await prisma.pendingRefund.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PendingRefundCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PendingRefundCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PendingRefund.
   * @param {PendingRefundDeleteArgs} args - Arguments to delete one PendingRefund.
   * @example
   * // Delete one PendingRefund
   * const PendingRefund = await prisma.pendingRefund.delete({
   *   where: {
   *     // ... filter to delete one PendingRefund
   *   }
   * })
   * 
   */
  delete<T extends PendingRefundDeleteArgs>(args: Prisma.SelectSubset<T, PendingRefundDeleteArgs<ExtArgs>>): Prisma.Prisma__PendingRefundClient<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PendingRefund.
   * @param {PendingRefundUpdateArgs} args - Arguments to update one PendingRefund.
   * @example
   * // Update one PendingRefund
   * const pendingRefund = await prisma.pendingRefund.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PendingRefundUpdateArgs>(args: Prisma.SelectSubset<T, PendingRefundUpdateArgs<ExtArgs>>): Prisma.Prisma__PendingRefundClient<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PendingRefunds.
   * @param {PendingRefundDeleteManyArgs} args - Arguments to filter PendingRefunds to delete.
   * @example
   * // Delete a few PendingRefunds
   * const { count } = await prisma.pendingRefund.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PendingRefundDeleteManyArgs>(args?: Prisma.SelectSubset<T, PendingRefundDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PendingRefunds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PendingRefundUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PendingRefunds
   * const pendingRefund = await prisma.pendingRefund.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PendingRefundUpdateManyArgs>(args: Prisma.SelectSubset<T, PendingRefundUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PendingRefunds and returns the data updated in the database.
   * @param {PendingRefundUpdateManyAndReturnArgs} args - Arguments to update many PendingRefunds.
   * @example
   * // Update many PendingRefunds
   * const pendingRefund = await prisma.pendingRefund.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PendingRefunds and only return the `id`
   * const pendingRefundWithIdOnly = await prisma.pendingRefund.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PendingRefundUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PendingRefundUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PendingRefund.
   * @param {PendingRefundUpsertArgs} args - Arguments to update or create a PendingRefund.
   * @example
   * // Update or create a PendingRefund
   * const pendingRefund = await prisma.pendingRefund.upsert({
   *   create: {
   *     // ... data to create a PendingRefund
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PendingRefund we want to update
   *   }
   * })
   */
  upsert<T extends PendingRefundUpsertArgs>(args: Prisma.SelectSubset<T, PendingRefundUpsertArgs<ExtArgs>>): Prisma.Prisma__PendingRefundClient<runtime.Types.Result.GetResult<Prisma.$PendingRefundPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PendingRefunds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PendingRefundCountArgs} args - Arguments to filter PendingRefunds to count.
   * @example
   * // Count the number of PendingRefunds
   * const count = await prisma.pendingRefund.count({
   *   where: {
   *     // ... the filter for the PendingRefunds we want to count
   *   }
   * })
  **/
  count<T extends PendingRefundCountArgs>(
    args?: Prisma.Subset<T, PendingRefundCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PendingRefundCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PendingRefund.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PendingRefundAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PendingRefundAggregateArgs>(args: Prisma.Subset<T, PendingRefundAggregateArgs>): Prisma.PrismaPromise<GetPendingRefundAggregateType<T>>

  /**
   * Group by PendingRefund.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PendingRefundGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PendingRefundGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PendingRefundGroupByArgs['orderBy'] }
      : { orderBy?: PendingRefundGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PendingRefundGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPendingRefundGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PendingRefund model
 */
readonly fields: PendingRefundFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PendingRefund.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PendingRefundClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PendingRefund model
 */
export interface PendingRefundFieldRefs {
  readonly id: Prisma.FieldRef<"PendingRefund", 'String'>
  readonly userId: Prisma.FieldRef<"PendingRefund", 'String'>
  readonly twitchUsername: Prisma.FieldRef<"PendingRefund", 'String'>
  readonly amount: Prisma.FieldRef<"PendingRefund", 'Int'>
  readonly reason: Prisma.FieldRef<"PendingRefund", 'String'>
  readonly wizebotDebitTxId: Prisma.FieldRef<"PendingRefund", 'String'>
  readonly status: Prisma.FieldRef<"PendingRefund", 'RefundStatus'>
  readonly attempts: Prisma.FieldRef<"PendingRefund", 'Int'>
  readonly lastError: Prisma.FieldRef<"PendingRefund", 'String'>
  readonly refundTxId: Prisma.FieldRef<"PendingRefund", 'String'>
  readonly refundedAt: Prisma.FieldRef<"PendingRefund", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"PendingRefund", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PendingRefund", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PendingRefund findUnique
 */
export type PendingRefundFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
  /**
   * Filter, which PendingRefund to fetch.
   */
  where: Prisma.PendingRefundWhereUniqueInput
}

/**
 * PendingRefund findUniqueOrThrow
 */
export type PendingRefundFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
  /**
   * Filter, which PendingRefund to fetch.
   */
  where: Prisma.PendingRefundWhereUniqueInput
}

/**
 * PendingRefund findFirst
 */
export type PendingRefundFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
  /**
   * Filter, which PendingRefund to fetch.
   */
  where?: Prisma.PendingRefundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PendingRefunds to fetch.
   */
  orderBy?: Prisma.PendingRefundOrderByWithRelationInput | Prisma.PendingRefundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PendingRefunds.
   */
  cursor?: Prisma.PendingRefundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PendingRefunds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PendingRefunds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PendingRefunds.
   */
  distinct?: Prisma.PendingRefundScalarFieldEnum | Prisma.PendingRefundScalarFieldEnum[]
}

/**
 * PendingRefund findFirstOrThrow
 */
export type PendingRefundFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
  /**
   * Filter, which PendingRefund to fetch.
   */
  where?: Prisma.PendingRefundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PendingRefunds to fetch.
   */
  orderBy?: Prisma.PendingRefundOrderByWithRelationInput | Prisma.PendingRefundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PendingRefunds.
   */
  cursor?: Prisma.PendingRefundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PendingRefunds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PendingRefunds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PendingRefunds.
   */
  distinct?: Prisma.PendingRefundScalarFieldEnum | Prisma.PendingRefundScalarFieldEnum[]
}

/**
 * PendingRefund findMany
 */
export type PendingRefundFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
  /**
   * Filter, which PendingRefunds to fetch.
   */
  where?: Prisma.PendingRefundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PendingRefunds to fetch.
   */
  orderBy?: Prisma.PendingRefundOrderByWithRelationInput | Prisma.PendingRefundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PendingRefunds.
   */
  cursor?: Prisma.PendingRefundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PendingRefunds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PendingRefunds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PendingRefunds.
   */
  distinct?: Prisma.PendingRefundScalarFieldEnum | Prisma.PendingRefundScalarFieldEnum[]
}

/**
 * PendingRefund create
 */
export type PendingRefundCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
  /**
   * The data needed to create a PendingRefund.
   */
  data: Prisma.XOR<Prisma.PendingRefundCreateInput, Prisma.PendingRefundUncheckedCreateInput>
}

/**
 * PendingRefund createMany
 */
export type PendingRefundCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PendingRefunds.
   */
  data: Prisma.PendingRefundCreateManyInput | Prisma.PendingRefundCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PendingRefund createManyAndReturn
 */
export type PendingRefundCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * The data used to create many PendingRefunds.
   */
  data: Prisma.PendingRefundCreateManyInput | Prisma.PendingRefundCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PendingRefund update
 */
export type PendingRefundUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
  /**
   * The data needed to update a PendingRefund.
   */
  data: Prisma.XOR<Prisma.PendingRefundUpdateInput, Prisma.PendingRefundUncheckedUpdateInput>
  /**
   * Choose, which PendingRefund to update.
   */
  where: Prisma.PendingRefundWhereUniqueInput
}

/**
 * PendingRefund updateMany
 */
export type PendingRefundUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PendingRefunds.
   */
  data: Prisma.XOR<Prisma.PendingRefundUpdateManyMutationInput, Prisma.PendingRefundUncheckedUpdateManyInput>
  /**
   * Filter which PendingRefunds to update
   */
  where?: Prisma.PendingRefundWhereInput
  /**
   * Limit how many PendingRefunds to update.
   */
  limit?: number
}

/**
 * PendingRefund updateManyAndReturn
 */
export type PendingRefundUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * The data used to update PendingRefunds.
   */
  data: Prisma.XOR<Prisma.PendingRefundUpdateManyMutationInput, Prisma.PendingRefundUncheckedUpdateManyInput>
  /**
   * Filter which PendingRefunds to update
   */
  where?: Prisma.PendingRefundWhereInput
  /**
   * Limit how many PendingRefunds to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PendingRefund upsert
 */
export type PendingRefundUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
  /**
   * The filter to search for the PendingRefund to update in case it exists.
   */
  where: Prisma.PendingRefundWhereUniqueInput
  /**
   * In case the PendingRefund found by the `where` argument doesn't exist, create a new PendingRefund with this data.
   */
  create: Prisma.XOR<Prisma.PendingRefundCreateInput, Prisma.PendingRefundUncheckedCreateInput>
  /**
   * In case the PendingRefund was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PendingRefundUpdateInput, Prisma.PendingRefundUncheckedUpdateInput>
}

/**
 * PendingRefund delete
 */
export type PendingRefundDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
  /**
   * Filter which PendingRefund to delete.
   */
  where: Prisma.PendingRefundWhereUniqueInput
}

/**
 * PendingRefund deleteMany
 */
export type PendingRefundDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PendingRefunds to delete
   */
  where?: Prisma.PendingRefundWhereInput
  /**
   * Limit how many PendingRefunds to delete.
   */
  limit?: number
}

/**
 * PendingRefund without action
 */
export type PendingRefundDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PendingRefund
   */
  select?: Prisma.PendingRefundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PendingRefund
   */
  omit?: Prisma.PendingRefundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PendingRefundInclude<ExtArgs> | null
}
