
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PointTransfer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PointTransfer
 * 
 */
export type PointTransferModel = runtime.Types.Result.DefaultSelection<Prisma.$PointTransferPayload>

export type AggregatePointTransfer = {
  _count: PointTransferCountAggregateOutputType | null
  _avg: PointTransferAvgAggregateOutputType | null
  _sum: PointTransferSumAggregateOutputType | null
  _min: PointTransferMinAggregateOutputType | null
  _max: PointTransferMaxAggregateOutputType | null
}

export type PointTransferAvgAggregateOutputType = {
  amount: number | null
}

export type PointTransferSumAggregateOutputType = {
  amount: number | null
}

export type PointTransferMinAggregateOutputType = {
  id: string | null
  senderId: string | null
  recipientId: string | null
  senderTwitch: string | null
  recipientTwitch: string | null
  amount: number | null
  note: string | null
  status: $Enums.TransferStatus | null
  debitTxId: string | null
  creditTxId: string | null
  error: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PointTransferMaxAggregateOutputType = {
  id: string | null
  senderId: string | null
  recipientId: string | null
  senderTwitch: string | null
  recipientTwitch: string | null
  amount: number | null
  note: string | null
  status: $Enums.TransferStatus | null
  debitTxId: string | null
  creditTxId: string | null
  error: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PointTransferCountAggregateOutputType = {
  id: number
  senderId: number
  recipientId: number
  senderTwitch: number
  recipientTwitch: number
  amount: number
  note: number
  status: number
  debitTxId: number
  creditTxId: number
  error: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PointTransferAvgAggregateInputType = {
  amount?: true
}

export type PointTransferSumAggregateInputType = {
  amount?: true
}

export type PointTransferMinAggregateInputType = {
  id?: true
  senderId?: true
  recipientId?: true
  senderTwitch?: true
  recipientTwitch?: true
  amount?: true
  note?: true
  status?: true
  debitTxId?: true
  creditTxId?: true
  error?: true
  createdAt?: true
  updatedAt?: true
}

export type PointTransferMaxAggregateInputType = {
  id?: true
  senderId?: true
  recipientId?: true
  senderTwitch?: true
  recipientTwitch?: true
  amount?: true
  note?: true
  status?: true
  debitTxId?: true
  creditTxId?: true
  error?: true
  createdAt?: true
  updatedAt?: true
}

export type PointTransferCountAggregateInputType = {
  id?: true
  senderId?: true
  recipientId?: true
  senderTwitch?: true
  recipientTwitch?: true
  amount?: true
  note?: true
  status?: true
  debitTxId?: true
  creditTxId?: true
  error?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PointTransferAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PointTransfer to aggregate.
   */
  where?: Prisma.PointTransferWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointTransfers to fetch.
   */
  orderBy?: Prisma.PointTransferOrderByWithRelationInput | Prisma.PointTransferOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PointTransferWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointTransfers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointTransfers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PointTransfers
  **/
  _count?: true | PointTransferCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PointTransferAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PointTransferSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PointTransferMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PointTransferMaxAggregateInputType
}

export type GetPointTransferAggregateType<T extends PointTransferAggregateArgs> = {
      [P in keyof T & keyof AggregatePointTransfer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePointTransfer[P]>
    : Prisma.GetScalarType<T[P], AggregatePointTransfer[P]>
}




export type PointTransferGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PointTransferWhereInput
  orderBy?: Prisma.PointTransferOrderByWithAggregationInput | Prisma.PointTransferOrderByWithAggregationInput[]
  by: Prisma.PointTransferScalarFieldEnum[] | Prisma.PointTransferScalarFieldEnum
  having?: Prisma.PointTransferScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PointTransferCountAggregateInputType | true
  _avg?: PointTransferAvgAggregateInputType
  _sum?: PointTransferSumAggregateInputType
  _min?: PointTransferMinAggregateInputType
  _max?: PointTransferMaxAggregateInputType
}

export type PointTransferGroupByOutputType = {
  id: string
  senderId: string
  recipientId: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note: string | null
  status: $Enums.TransferStatus
  debitTxId: string | null
  creditTxId: string | null
  error: string | null
  createdAt: Date
  updatedAt: Date
  _count: PointTransferCountAggregateOutputType | null
  _avg: PointTransferAvgAggregateOutputType | null
  _sum: PointTransferSumAggregateOutputType | null
  _min: PointTransferMinAggregateOutputType | null
  _max: PointTransferMaxAggregateOutputType | null
}

export type GetPointTransferGroupByPayload<T extends PointTransferGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PointTransferGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PointTransferGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PointTransferGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PointTransferGroupByOutputType[P]>
      }
    >
  >



export type PointTransferWhereInput = {
  AND?: Prisma.PointTransferWhereInput | Prisma.PointTransferWhereInput[]
  OR?: Prisma.PointTransferWhereInput[]
  NOT?: Prisma.PointTransferWhereInput | Prisma.PointTransferWhereInput[]
  id?: Prisma.UuidFilter<"PointTransfer"> | string
  senderId?: Prisma.UuidFilter<"PointTransfer"> | string
  recipientId?: Prisma.UuidFilter<"PointTransfer"> | string
  senderTwitch?: Prisma.StringFilter<"PointTransfer"> | string
  recipientTwitch?: Prisma.StringFilter<"PointTransfer"> | string
  amount?: Prisma.IntFilter<"PointTransfer"> | number
  note?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  status?: Prisma.EnumTransferStatusFilter<"PointTransfer"> | $Enums.TransferStatus
  debitTxId?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  creditTxId?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  error?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PointTransfer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PointTransfer"> | Date | string
  sender?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  recipient?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PointTransferOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  recipientId?: Prisma.SortOrder
  senderTwitch?: Prisma.SortOrder
  recipientTwitch?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  debitTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  creditTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  sender?: Prisma.UserOrderByWithRelationInput
  recipient?: Prisma.UserOrderByWithRelationInput
}

export type PointTransferWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PointTransferWhereInput | Prisma.PointTransferWhereInput[]
  OR?: Prisma.PointTransferWhereInput[]
  NOT?: Prisma.PointTransferWhereInput | Prisma.PointTransferWhereInput[]
  senderId?: Prisma.UuidFilter<"PointTransfer"> | string
  recipientId?: Prisma.UuidFilter<"PointTransfer"> | string
  senderTwitch?: Prisma.StringFilter<"PointTransfer"> | string
  recipientTwitch?: Prisma.StringFilter<"PointTransfer"> | string
  amount?: Prisma.IntFilter<"PointTransfer"> | number
  note?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  status?: Prisma.EnumTransferStatusFilter<"PointTransfer"> | $Enums.TransferStatus
  debitTxId?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  creditTxId?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  error?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PointTransfer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PointTransfer"> | Date | string
  sender?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  recipient?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type PointTransferOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  recipientId?: Prisma.SortOrder
  senderTwitch?: Prisma.SortOrder
  recipientTwitch?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  debitTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  creditTxId?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PointTransferCountOrderByAggregateInput
  _avg?: Prisma.PointTransferAvgOrderByAggregateInput
  _max?: Prisma.PointTransferMaxOrderByAggregateInput
  _min?: Prisma.PointTransferMinOrderByAggregateInput
  _sum?: Prisma.PointTransferSumOrderByAggregateInput
}

export type PointTransferScalarWhereWithAggregatesInput = {
  AND?: Prisma.PointTransferScalarWhereWithAggregatesInput | Prisma.PointTransferScalarWhereWithAggregatesInput[]
  OR?: Prisma.PointTransferScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PointTransferScalarWhereWithAggregatesInput | Prisma.PointTransferScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"PointTransfer"> | string
  senderId?: Prisma.UuidWithAggregatesFilter<"PointTransfer"> | string
  recipientId?: Prisma.UuidWithAggregatesFilter<"PointTransfer"> | string
  senderTwitch?: Prisma.StringWithAggregatesFilter<"PointTransfer"> | string
  recipientTwitch?: Prisma.StringWithAggregatesFilter<"PointTransfer"> | string
  amount?: Prisma.IntWithAggregatesFilter<"PointTransfer"> | number
  note?: Prisma.StringNullableWithAggregatesFilter<"PointTransfer"> | string | null
  status?: Prisma.EnumTransferStatusWithAggregatesFilter<"PointTransfer"> | $Enums.TransferStatus
  debitTxId?: Prisma.StringNullableWithAggregatesFilter<"PointTransfer"> | string | null
  creditTxId?: Prisma.StringNullableWithAggregatesFilter<"PointTransfer"> | string | null
  error?: Prisma.StringNullableWithAggregatesFilter<"PointTransfer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PointTransfer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PointTransfer"> | Date | string
}

export type PointTransferCreateInput = {
  id?: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note?: string | null
  status?: $Enums.TransferStatus
  debitTxId?: string | null
  creditTxId?: string | null
  error?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sender: Prisma.UserCreateNestedOneWithoutTransfersSentInput
  recipient: Prisma.UserCreateNestedOneWithoutTransfersReceivedInput
}

export type PointTransferUncheckedCreateInput = {
  id?: string
  senderId: string
  recipientId: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note?: string | null
  status?: $Enums.TransferStatus
  debitTxId?: string | null
  creditTxId?: string | null
  error?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PointTransferUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sender?: Prisma.UserUpdateOneRequiredWithoutTransfersSentNestedInput
  recipient?: Prisma.UserUpdateOneRequiredWithoutTransfersReceivedNestedInput
}

export type PointTransferUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  recipientId?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PointTransferCreateManyInput = {
  id?: string
  senderId: string
  recipientId: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note?: string | null
  status?: $Enums.TransferStatus
  debitTxId?: string | null
  creditTxId?: string | null
  error?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PointTransferUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PointTransferUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  recipientId?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PointTransferListRelationFilter = {
  every?: Prisma.PointTransferWhereInput
  some?: Prisma.PointTransferWhereInput
  none?: Prisma.PointTransferWhereInput
}

export type PointTransferOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PointTransferCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  recipientId?: Prisma.SortOrder
  senderTwitch?: Prisma.SortOrder
  recipientTwitch?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrder
  status?: Prisma.SortOrder
  debitTxId?: Prisma.SortOrder
  creditTxId?: Prisma.SortOrder
  error?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PointTransferAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PointTransferMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  recipientId?: Prisma.SortOrder
  senderTwitch?: Prisma.SortOrder
  recipientTwitch?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrder
  status?: Prisma.SortOrder
  debitTxId?: Prisma.SortOrder
  creditTxId?: Prisma.SortOrder
  error?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PointTransferMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  senderId?: Prisma.SortOrder
  recipientId?: Prisma.SortOrder
  senderTwitch?: Prisma.SortOrder
  recipientTwitch?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  note?: Prisma.SortOrder
  status?: Prisma.SortOrder
  debitTxId?: Prisma.SortOrder
  creditTxId?: Prisma.SortOrder
  error?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PointTransferSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PointTransferCreateNestedManyWithoutSenderInput = {
  create?: Prisma.XOR<Prisma.PointTransferCreateWithoutSenderInput, Prisma.PointTransferUncheckedCreateWithoutSenderInput> | Prisma.PointTransferCreateWithoutSenderInput[] | Prisma.PointTransferUncheckedCreateWithoutSenderInput[]
  connectOrCreate?: Prisma.PointTransferCreateOrConnectWithoutSenderInput | Prisma.PointTransferCreateOrConnectWithoutSenderInput[]
  createMany?: Prisma.PointTransferCreateManySenderInputEnvelope
  connect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
}

export type PointTransferCreateNestedManyWithoutRecipientInput = {
  create?: Prisma.XOR<Prisma.PointTransferCreateWithoutRecipientInput, Prisma.PointTransferUncheckedCreateWithoutRecipientInput> | Prisma.PointTransferCreateWithoutRecipientInput[] | Prisma.PointTransferUncheckedCreateWithoutRecipientInput[]
  connectOrCreate?: Prisma.PointTransferCreateOrConnectWithoutRecipientInput | Prisma.PointTransferCreateOrConnectWithoutRecipientInput[]
  createMany?: Prisma.PointTransferCreateManyRecipientInputEnvelope
  connect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
}

export type PointTransferUncheckedCreateNestedManyWithoutSenderInput = {
  create?: Prisma.XOR<Prisma.PointTransferCreateWithoutSenderInput, Prisma.PointTransferUncheckedCreateWithoutSenderInput> | Prisma.PointTransferCreateWithoutSenderInput[] | Prisma.PointTransferUncheckedCreateWithoutSenderInput[]
  connectOrCreate?: Prisma.PointTransferCreateOrConnectWithoutSenderInput | Prisma.PointTransferCreateOrConnectWithoutSenderInput[]
  createMany?: Prisma.PointTransferCreateManySenderInputEnvelope
  connect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
}

export type PointTransferUncheckedCreateNestedManyWithoutRecipientInput = {
  create?: Prisma.XOR<Prisma.PointTransferCreateWithoutRecipientInput, Prisma.PointTransferUncheckedCreateWithoutRecipientInput> | Prisma.PointTransferCreateWithoutRecipientInput[] | Prisma.PointTransferUncheckedCreateWithoutRecipientInput[]
  connectOrCreate?: Prisma.PointTransferCreateOrConnectWithoutRecipientInput | Prisma.PointTransferCreateOrConnectWithoutRecipientInput[]
  createMany?: Prisma.PointTransferCreateManyRecipientInputEnvelope
  connect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
}

export type PointTransferUpdateManyWithoutSenderNestedInput = {
  create?: Prisma.XOR<Prisma.PointTransferCreateWithoutSenderInput, Prisma.PointTransferUncheckedCreateWithoutSenderInput> | Prisma.PointTransferCreateWithoutSenderInput[] | Prisma.PointTransferUncheckedCreateWithoutSenderInput[]
  connectOrCreate?: Prisma.PointTransferCreateOrConnectWithoutSenderInput | Prisma.PointTransferCreateOrConnectWithoutSenderInput[]
  upsert?: Prisma.PointTransferUpsertWithWhereUniqueWithoutSenderInput | Prisma.PointTransferUpsertWithWhereUniqueWithoutSenderInput[]
  createMany?: Prisma.PointTransferCreateManySenderInputEnvelope
  set?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  disconnect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  delete?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  connect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  update?: Prisma.PointTransferUpdateWithWhereUniqueWithoutSenderInput | Prisma.PointTransferUpdateWithWhereUniqueWithoutSenderInput[]
  updateMany?: Prisma.PointTransferUpdateManyWithWhereWithoutSenderInput | Prisma.PointTransferUpdateManyWithWhereWithoutSenderInput[]
  deleteMany?: Prisma.PointTransferScalarWhereInput | Prisma.PointTransferScalarWhereInput[]
}

export type PointTransferUpdateManyWithoutRecipientNestedInput = {
  create?: Prisma.XOR<Prisma.PointTransferCreateWithoutRecipientInput, Prisma.PointTransferUncheckedCreateWithoutRecipientInput> | Prisma.PointTransferCreateWithoutRecipientInput[] | Prisma.PointTransferUncheckedCreateWithoutRecipientInput[]
  connectOrCreate?: Prisma.PointTransferCreateOrConnectWithoutRecipientInput | Prisma.PointTransferCreateOrConnectWithoutRecipientInput[]
  upsert?: Prisma.PointTransferUpsertWithWhereUniqueWithoutRecipientInput | Prisma.PointTransferUpsertWithWhereUniqueWithoutRecipientInput[]
  createMany?: Prisma.PointTransferCreateManyRecipientInputEnvelope
  set?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  disconnect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  delete?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  connect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  update?: Prisma.PointTransferUpdateWithWhereUniqueWithoutRecipientInput | Prisma.PointTransferUpdateWithWhereUniqueWithoutRecipientInput[]
  updateMany?: Prisma.PointTransferUpdateManyWithWhereWithoutRecipientInput | Prisma.PointTransferUpdateManyWithWhereWithoutRecipientInput[]
  deleteMany?: Prisma.PointTransferScalarWhereInput | Prisma.PointTransferScalarWhereInput[]
}

export type PointTransferUncheckedUpdateManyWithoutSenderNestedInput = {
  create?: Prisma.XOR<Prisma.PointTransferCreateWithoutSenderInput, Prisma.PointTransferUncheckedCreateWithoutSenderInput> | Prisma.PointTransferCreateWithoutSenderInput[] | Prisma.PointTransferUncheckedCreateWithoutSenderInput[]
  connectOrCreate?: Prisma.PointTransferCreateOrConnectWithoutSenderInput | Prisma.PointTransferCreateOrConnectWithoutSenderInput[]
  upsert?: Prisma.PointTransferUpsertWithWhereUniqueWithoutSenderInput | Prisma.PointTransferUpsertWithWhereUniqueWithoutSenderInput[]
  createMany?: Prisma.PointTransferCreateManySenderInputEnvelope
  set?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  disconnect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  delete?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  connect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  update?: Prisma.PointTransferUpdateWithWhereUniqueWithoutSenderInput | Prisma.PointTransferUpdateWithWhereUniqueWithoutSenderInput[]
  updateMany?: Prisma.PointTransferUpdateManyWithWhereWithoutSenderInput | Prisma.PointTransferUpdateManyWithWhereWithoutSenderInput[]
  deleteMany?: Prisma.PointTransferScalarWhereInput | Prisma.PointTransferScalarWhereInput[]
}

export type PointTransferUncheckedUpdateManyWithoutRecipientNestedInput = {
  create?: Prisma.XOR<Prisma.PointTransferCreateWithoutRecipientInput, Prisma.PointTransferUncheckedCreateWithoutRecipientInput> | Prisma.PointTransferCreateWithoutRecipientInput[] | Prisma.PointTransferUncheckedCreateWithoutRecipientInput[]
  connectOrCreate?: Prisma.PointTransferCreateOrConnectWithoutRecipientInput | Prisma.PointTransferCreateOrConnectWithoutRecipientInput[]
  upsert?: Prisma.PointTransferUpsertWithWhereUniqueWithoutRecipientInput | Prisma.PointTransferUpsertWithWhereUniqueWithoutRecipientInput[]
  createMany?: Prisma.PointTransferCreateManyRecipientInputEnvelope
  set?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  disconnect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  delete?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  connect?: Prisma.PointTransferWhereUniqueInput | Prisma.PointTransferWhereUniqueInput[]
  update?: Prisma.PointTransferUpdateWithWhereUniqueWithoutRecipientInput | Prisma.PointTransferUpdateWithWhereUniqueWithoutRecipientInput[]
  updateMany?: Prisma.PointTransferUpdateManyWithWhereWithoutRecipientInput | Prisma.PointTransferUpdateManyWithWhereWithoutRecipientInput[]
  deleteMany?: Prisma.PointTransferScalarWhereInput | Prisma.PointTransferScalarWhereInput[]
}

export type EnumTransferStatusFieldUpdateOperationsInput = {
  set?: $Enums.TransferStatus
}

export type PointTransferCreateWithoutSenderInput = {
  id?: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note?: string | null
  status?: $Enums.TransferStatus
  debitTxId?: string | null
  creditTxId?: string | null
  error?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  recipient: Prisma.UserCreateNestedOneWithoutTransfersReceivedInput
}

export type PointTransferUncheckedCreateWithoutSenderInput = {
  id?: string
  recipientId: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note?: string | null
  status?: $Enums.TransferStatus
  debitTxId?: string | null
  creditTxId?: string | null
  error?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PointTransferCreateOrConnectWithoutSenderInput = {
  where: Prisma.PointTransferWhereUniqueInput
  create: Prisma.XOR<Prisma.PointTransferCreateWithoutSenderInput, Prisma.PointTransferUncheckedCreateWithoutSenderInput>
}

export type PointTransferCreateManySenderInputEnvelope = {
  data: Prisma.PointTransferCreateManySenderInput | Prisma.PointTransferCreateManySenderInput[]
  skipDuplicates?: boolean
}

export type PointTransferCreateWithoutRecipientInput = {
  id?: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note?: string | null
  status?: $Enums.TransferStatus
  debitTxId?: string | null
  creditTxId?: string | null
  error?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sender: Prisma.UserCreateNestedOneWithoutTransfersSentInput
}

export type PointTransferUncheckedCreateWithoutRecipientInput = {
  id?: string
  senderId: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note?: string | null
  status?: $Enums.TransferStatus
  debitTxId?: string | null
  creditTxId?: string | null
  error?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PointTransferCreateOrConnectWithoutRecipientInput = {
  where: Prisma.PointTransferWhereUniqueInput
  create: Prisma.XOR<Prisma.PointTransferCreateWithoutRecipientInput, Prisma.PointTransferUncheckedCreateWithoutRecipientInput>
}

export type PointTransferCreateManyRecipientInputEnvelope = {
  data: Prisma.PointTransferCreateManyRecipientInput | Prisma.PointTransferCreateManyRecipientInput[]
  skipDuplicates?: boolean
}

export type PointTransferUpsertWithWhereUniqueWithoutSenderInput = {
  where: Prisma.PointTransferWhereUniqueInput
  update: Prisma.XOR<Prisma.PointTransferUpdateWithoutSenderInput, Prisma.PointTransferUncheckedUpdateWithoutSenderInput>
  create: Prisma.XOR<Prisma.PointTransferCreateWithoutSenderInput, Prisma.PointTransferUncheckedCreateWithoutSenderInput>
}

export type PointTransferUpdateWithWhereUniqueWithoutSenderInput = {
  where: Prisma.PointTransferWhereUniqueInput
  data: Prisma.XOR<Prisma.PointTransferUpdateWithoutSenderInput, Prisma.PointTransferUncheckedUpdateWithoutSenderInput>
}

export type PointTransferUpdateManyWithWhereWithoutSenderInput = {
  where: Prisma.PointTransferScalarWhereInput
  data: Prisma.XOR<Prisma.PointTransferUpdateManyMutationInput, Prisma.PointTransferUncheckedUpdateManyWithoutSenderInput>
}

export type PointTransferScalarWhereInput = {
  AND?: Prisma.PointTransferScalarWhereInput | Prisma.PointTransferScalarWhereInput[]
  OR?: Prisma.PointTransferScalarWhereInput[]
  NOT?: Prisma.PointTransferScalarWhereInput | Prisma.PointTransferScalarWhereInput[]
  id?: Prisma.UuidFilter<"PointTransfer"> | string
  senderId?: Prisma.UuidFilter<"PointTransfer"> | string
  recipientId?: Prisma.UuidFilter<"PointTransfer"> | string
  senderTwitch?: Prisma.StringFilter<"PointTransfer"> | string
  recipientTwitch?: Prisma.StringFilter<"PointTransfer"> | string
  amount?: Prisma.IntFilter<"PointTransfer"> | number
  note?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  status?: Prisma.EnumTransferStatusFilter<"PointTransfer"> | $Enums.TransferStatus
  debitTxId?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  creditTxId?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  error?: Prisma.StringNullableFilter<"PointTransfer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PointTransfer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PointTransfer"> | Date | string
}

export type PointTransferUpsertWithWhereUniqueWithoutRecipientInput = {
  where: Prisma.PointTransferWhereUniqueInput
  update: Prisma.XOR<Prisma.PointTransferUpdateWithoutRecipientInput, Prisma.PointTransferUncheckedUpdateWithoutRecipientInput>
  create: Prisma.XOR<Prisma.PointTransferCreateWithoutRecipientInput, Prisma.PointTransferUncheckedCreateWithoutRecipientInput>
}

export type PointTransferUpdateWithWhereUniqueWithoutRecipientInput = {
  where: Prisma.PointTransferWhereUniqueInput
  data: Prisma.XOR<Prisma.PointTransferUpdateWithoutRecipientInput, Prisma.PointTransferUncheckedUpdateWithoutRecipientInput>
}

export type PointTransferUpdateManyWithWhereWithoutRecipientInput = {
  where: Prisma.PointTransferScalarWhereInput
  data: Prisma.XOR<Prisma.PointTransferUpdateManyMutationInput, Prisma.PointTransferUncheckedUpdateManyWithoutRecipientInput>
}

export type PointTransferCreateManySenderInput = {
  id?: string
  recipientId: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note?: string | null
  status?: $Enums.TransferStatus
  debitTxId?: string | null
  creditTxId?: string | null
  error?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PointTransferCreateManyRecipientInput = {
  id?: string
  senderId: string
  senderTwitch: string
  recipientTwitch: string
  amount: number
  note?: string | null
  status?: $Enums.TransferStatus
  debitTxId?: string | null
  creditTxId?: string | null
  error?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PointTransferUpdateWithoutSenderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recipient?: Prisma.UserUpdateOneRequiredWithoutTransfersReceivedNestedInput
}

export type PointTransferUncheckedUpdateWithoutSenderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipientId?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PointTransferUncheckedUpdateManyWithoutSenderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipientId?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PointTransferUpdateWithoutRecipientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sender?: Prisma.UserUpdateOneRequiredWithoutTransfersSentNestedInput
}

export type PointTransferUncheckedUpdateWithoutRecipientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PointTransferUncheckedUpdateManyWithoutRecipientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderId?: Prisma.StringFieldUpdateOperationsInput | string
  senderTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  recipientTwitch?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTransferStatusFieldUpdateOperationsInput | $Enums.TransferStatus
  debitTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditTxId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PointTransferSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  senderId?: boolean
  recipientId?: boolean
  senderTwitch?: boolean
  recipientTwitch?: boolean
  amount?: boolean
  note?: boolean
  status?: boolean
  debitTxId?: boolean
  creditTxId?: boolean
  error?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sender?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  recipient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pointTransfer"]>

export type PointTransferSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  senderId?: boolean
  recipientId?: boolean
  senderTwitch?: boolean
  recipientTwitch?: boolean
  amount?: boolean
  note?: boolean
  status?: boolean
  debitTxId?: boolean
  creditTxId?: boolean
  error?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sender?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  recipient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pointTransfer"]>

export type PointTransferSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  senderId?: boolean
  recipientId?: boolean
  senderTwitch?: boolean
  recipientTwitch?: boolean
  amount?: boolean
  note?: boolean
  status?: boolean
  debitTxId?: boolean
  creditTxId?: boolean
  error?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sender?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  recipient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pointTransfer"]>

export type PointTransferSelectScalar = {
  id?: boolean
  senderId?: boolean
  recipientId?: boolean
  senderTwitch?: boolean
  recipientTwitch?: boolean
  amount?: boolean
  note?: boolean
  status?: boolean
  debitTxId?: boolean
  creditTxId?: boolean
  error?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PointTransferOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "senderId" | "recipientId" | "senderTwitch" | "recipientTwitch" | "amount" | "note" | "status" | "debitTxId" | "creditTxId" | "error" | "createdAt" | "updatedAt", ExtArgs["result"]["pointTransfer"]>
export type PointTransferInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sender?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  recipient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PointTransferIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sender?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  recipient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PointTransferIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sender?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  recipient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PointTransferPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PointTransfer"
  objects: {
    sender: Prisma.$UserPayload<ExtArgs>
    recipient: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    senderId: string
    recipientId: string
    senderTwitch: string
    recipientTwitch: string
    amount: number
    note: string | null
    status: $Enums.TransferStatus
    debitTxId: string | null
    creditTxId: string | null
    error: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pointTransfer"]>
  composites: {}
}

export type PointTransferGetPayload<S extends boolean | null | undefined | PointTransferDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PointTransferPayload, S>

export type PointTransferCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PointTransferFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PointTransferCountAggregateInputType | true
  }

export interface PointTransferDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PointTransfer'], meta: { name: 'PointTransfer' } }
  /**
   * Find zero or one PointTransfer that matches the filter.
   * @param {PointTransferFindUniqueArgs} args - Arguments to find a PointTransfer
   * @example
   * // Get one PointTransfer
   * const pointTransfer = await prisma.pointTransfer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PointTransferFindUniqueArgs>(args: Prisma.SelectSubset<T, PointTransferFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PointTransferClient<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PointTransfer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PointTransferFindUniqueOrThrowArgs} args - Arguments to find a PointTransfer
   * @example
   * // Get one PointTransfer
   * const pointTransfer = await prisma.pointTransfer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PointTransferFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PointTransferFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PointTransferClient<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PointTransfer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointTransferFindFirstArgs} args - Arguments to find a PointTransfer
   * @example
   * // Get one PointTransfer
   * const pointTransfer = await prisma.pointTransfer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PointTransferFindFirstArgs>(args?: Prisma.SelectSubset<T, PointTransferFindFirstArgs<ExtArgs>>): Prisma.Prisma__PointTransferClient<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PointTransfer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointTransferFindFirstOrThrowArgs} args - Arguments to find a PointTransfer
   * @example
   * // Get one PointTransfer
   * const pointTransfer = await prisma.pointTransfer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PointTransferFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PointTransferFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PointTransferClient<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PointTransfers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointTransferFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PointTransfers
   * const pointTransfers = await prisma.pointTransfer.findMany()
   * 
   * // Get first 10 PointTransfers
   * const pointTransfers = await prisma.pointTransfer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pointTransferWithIdOnly = await prisma.pointTransfer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PointTransferFindManyArgs>(args?: Prisma.SelectSubset<T, PointTransferFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PointTransfer.
   * @param {PointTransferCreateArgs} args - Arguments to create a PointTransfer.
   * @example
   * // Create one PointTransfer
   * const PointTransfer = await prisma.pointTransfer.create({
   *   data: {
   *     // ... data to create a PointTransfer
   *   }
   * })
   * 
   */
  create<T extends PointTransferCreateArgs>(args: Prisma.SelectSubset<T, PointTransferCreateArgs<ExtArgs>>): Prisma.Prisma__PointTransferClient<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PointTransfers.
   * @param {PointTransferCreateManyArgs} args - Arguments to create many PointTransfers.
   * @example
   * // Create many PointTransfers
   * const pointTransfer = await prisma.pointTransfer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PointTransferCreateManyArgs>(args?: Prisma.SelectSubset<T, PointTransferCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PointTransfers and returns the data saved in the database.
   * @param {PointTransferCreateManyAndReturnArgs} args - Arguments to create many PointTransfers.
   * @example
   * // Create many PointTransfers
   * const pointTransfer = await prisma.pointTransfer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PointTransfers and only return the `id`
   * const pointTransferWithIdOnly = await prisma.pointTransfer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PointTransferCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PointTransferCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PointTransfer.
   * @param {PointTransferDeleteArgs} args - Arguments to delete one PointTransfer.
   * @example
   * // Delete one PointTransfer
   * const PointTransfer = await prisma.pointTransfer.delete({
   *   where: {
   *     // ... filter to delete one PointTransfer
   *   }
   * })
   * 
   */
  delete<T extends PointTransferDeleteArgs>(args: Prisma.SelectSubset<T, PointTransferDeleteArgs<ExtArgs>>): Prisma.Prisma__PointTransferClient<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PointTransfer.
   * @param {PointTransferUpdateArgs} args - Arguments to update one PointTransfer.
   * @example
   * // Update one PointTransfer
   * const pointTransfer = await prisma.pointTransfer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PointTransferUpdateArgs>(args: Prisma.SelectSubset<T, PointTransferUpdateArgs<ExtArgs>>): Prisma.Prisma__PointTransferClient<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PointTransfers.
   * @param {PointTransferDeleteManyArgs} args - Arguments to filter PointTransfers to delete.
   * @example
   * // Delete a few PointTransfers
   * const { count } = await prisma.pointTransfer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PointTransferDeleteManyArgs>(args?: Prisma.SelectSubset<T, PointTransferDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PointTransfers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointTransferUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PointTransfers
   * const pointTransfer = await prisma.pointTransfer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PointTransferUpdateManyArgs>(args: Prisma.SelectSubset<T, PointTransferUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PointTransfers and returns the data updated in the database.
   * @param {PointTransferUpdateManyAndReturnArgs} args - Arguments to update many PointTransfers.
   * @example
   * // Update many PointTransfers
   * const pointTransfer = await prisma.pointTransfer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PointTransfers and only return the `id`
   * const pointTransferWithIdOnly = await prisma.pointTransfer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PointTransferUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PointTransferUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PointTransfer.
   * @param {PointTransferUpsertArgs} args - Arguments to update or create a PointTransfer.
   * @example
   * // Update or create a PointTransfer
   * const pointTransfer = await prisma.pointTransfer.upsert({
   *   create: {
   *     // ... data to create a PointTransfer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PointTransfer we want to update
   *   }
   * })
   */
  upsert<T extends PointTransferUpsertArgs>(args: Prisma.SelectSubset<T, PointTransferUpsertArgs<ExtArgs>>): Prisma.Prisma__PointTransferClient<runtime.Types.Result.GetResult<Prisma.$PointTransferPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PointTransfers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointTransferCountArgs} args - Arguments to filter PointTransfers to count.
   * @example
   * // Count the number of PointTransfers
   * const count = await prisma.pointTransfer.count({
   *   where: {
   *     // ... the filter for the PointTransfers we want to count
   *   }
   * })
  **/
  count<T extends PointTransferCountArgs>(
    args?: Prisma.Subset<T, PointTransferCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PointTransferCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PointTransfer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointTransferAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PointTransferAggregateArgs>(args: Prisma.Subset<T, PointTransferAggregateArgs>): Prisma.PrismaPromise<GetPointTransferAggregateType<T>>

  /**
   * Group by PointTransfer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PointTransferGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PointTransferGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PointTransferGroupByArgs['orderBy'] }
      : { orderBy?: PointTransferGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PointTransferGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPointTransferGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PointTransfer model
 */
readonly fields: PointTransferFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PointTransfer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PointTransferClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sender<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  recipient<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PointTransfer model
 */
export interface PointTransferFieldRefs {
  readonly id: Prisma.FieldRef<"PointTransfer", 'String'>
  readonly senderId: Prisma.FieldRef<"PointTransfer", 'String'>
  readonly recipientId: Prisma.FieldRef<"PointTransfer", 'String'>
  readonly senderTwitch: Prisma.FieldRef<"PointTransfer", 'String'>
  readonly recipientTwitch: Prisma.FieldRef<"PointTransfer", 'String'>
  readonly amount: Prisma.FieldRef<"PointTransfer", 'Int'>
  readonly note: Prisma.FieldRef<"PointTransfer", 'String'>
  readonly status: Prisma.FieldRef<"PointTransfer", 'TransferStatus'>
  readonly debitTxId: Prisma.FieldRef<"PointTransfer", 'String'>
  readonly creditTxId: Prisma.FieldRef<"PointTransfer", 'String'>
  readonly error: Prisma.FieldRef<"PointTransfer", 'String'>
  readonly createdAt: Prisma.FieldRef<"PointTransfer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PointTransfer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PointTransfer findUnique
 */
export type PointTransferFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
  /**
   * Filter, which PointTransfer to fetch.
   */
  where: Prisma.PointTransferWhereUniqueInput
}

/**
 * PointTransfer findUniqueOrThrow
 */
export type PointTransferFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
  /**
   * Filter, which PointTransfer to fetch.
   */
  where: Prisma.PointTransferWhereUniqueInput
}

/**
 * PointTransfer findFirst
 */
export type PointTransferFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
  /**
   * Filter, which PointTransfer to fetch.
   */
  where?: Prisma.PointTransferWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointTransfers to fetch.
   */
  orderBy?: Prisma.PointTransferOrderByWithRelationInput | Prisma.PointTransferOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PointTransfers.
   */
  cursor?: Prisma.PointTransferWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointTransfers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointTransfers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PointTransfers.
   */
  distinct?: Prisma.PointTransferScalarFieldEnum | Prisma.PointTransferScalarFieldEnum[]
}

/**
 * PointTransfer findFirstOrThrow
 */
export type PointTransferFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
  /**
   * Filter, which PointTransfer to fetch.
   */
  where?: Prisma.PointTransferWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointTransfers to fetch.
   */
  orderBy?: Prisma.PointTransferOrderByWithRelationInput | Prisma.PointTransferOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PointTransfers.
   */
  cursor?: Prisma.PointTransferWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointTransfers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointTransfers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PointTransfers.
   */
  distinct?: Prisma.PointTransferScalarFieldEnum | Prisma.PointTransferScalarFieldEnum[]
}

/**
 * PointTransfer findMany
 */
export type PointTransferFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
  /**
   * Filter, which PointTransfers to fetch.
   */
  where?: Prisma.PointTransferWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PointTransfers to fetch.
   */
  orderBy?: Prisma.PointTransferOrderByWithRelationInput | Prisma.PointTransferOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PointTransfers.
   */
  cursor?: Prisma.PointTransferWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PointTransfers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PointTransfers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PointTransfers.
   */
  distinct?: Prisma.PointTransferScalarFieldEnum | Prisma.PointTransferScalarFieldEnum[]
}

/**
 * PointTransfer create
 */
export type PointTransferCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
  /**
   * The data needed to create a PointTransfer.
   */
  data: Prisma.XOR<Prisma.PointTransferCreateInput, Prisma.PointTransferUncheckedCreateInput>
}

/**
 * PointTransfer createMany
 */
export type PointTransferCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PointTransfers.
   */
  data: Prisma.PointTransferCreateManyInput | Prisma.PointTransferCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PointTransfer createManyAndReturn
 */
export type PointTransferCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * The data used to create many PointTransfers.
   */
  data: Prisma.PointTransferCreateManyInput | Prisma.PointTransferCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PointTransfer update
 */
export type PointTransferUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
  /**
   * The data needed to update a PointTransfer.
   */
  data: Prisma.XOR<Prisma.PointTransferUpdateInput, Prisma.PointTransferUncheckedUpdateInput>
  /**
   * Choose, which PointTransfer to update.
   */
  where: Prisma.PointTransferWhereUniqueInput
}

/**
 * PointTransfer updateMany
 */
export type PointTransferUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PointTransfers.
   */
  data: Prisma.XOR<Prisma.PointTransferUpdateManyMutationInput, Prisma.PointTransferUncheckedUpdateManyInput>
  /**
   * Filter which PointTransfers to update
   */
  where?: Prisma.PointTransferWhereInput
  /**
   * Limit how many PointTransfers to update.
   */
  limit?: number
}

/**
 * PointTransfer updateManyAndReturn
 */
export type PointTransferUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * The data used to update PointTransfers.
   */
  data: Prisma.XOR<Prisma.PointTransferUpdateManyMutationInput, Prisma.PointTransferUncheckedUpdateManyInput>
  /**
   * Filter which PointTransfers to update
   */
  where?: Prisma.PointTransferWhereInput
  /**
   * Limit how many PointTransfers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PointTransfer upsert
 */
export type PointTransferUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
  /**
   * The filter to search for the PointTransfer to update in case it exists.
   */
  where: Prisma.PointTransferWhereUniqueInput
  /**
   * In case the PointTransfer found by the `where` argument doesn't exist, create a new PointTransfer with this data.
   */
  create: Prisma.XOR<Prisma.PointTransferCreateInput, Prisma.PointTransferUncheckedCreateInput>
  /**
   * In case the PointTransfer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PointTransferUpdateInput, Prisma.PointTransferUncheckedUpdateInput>
}

/**
 * PointTransfer delete
 */
export type PointTransferDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
  /**
   * Filter which PointTransfer to delete.
   */
  where: Prisma.PointTransferWhereUniqueInput
}

/**
 * PointTransfer deleteMany
 */
export type PointTransferDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PointTransfers to delete
   */
  where?: Prisma.PointTransferWhereInput
  /**
   * Limit how many PointTransfers to delete.
   */
  limit?: number
}

/**
 * PointTransfer without action
 */
export type PointTransferDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PointTransfer
   */
  select?: Prisma.PointTransferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PointTransfer
   */
  omit?: Prisma.PointTransferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointTransferInclude<ExtArgs> | null
}
